import type { ProviderType } from '@/types';
import type { ProviderAdapter } from './types';
import { openaiAdapter } from './openai-adapter';
import { anthropicAdapter } from './anthropic-adapter';
import { googleAdapter } from './google-adapter';
import { deepseekAdapter } from './deepseek-adapter';
import { openrouterAdapter } from './openrouter-adapter';
import { mistralAdapter } from './mistral-adapter';
import { azureAdapter } from './azure-adapter';
import { xaiAdapter } from './xai-adapter';
import { cohereAdapter } from './cohere-adapter';
import { groqAdapter } from './groq-adapter';
import { togetherAdapter } from './together-adapter';
import { fireworksAdapter } from './fireworks-adapter';
import { perplexityAdapter } from './perplexity-adapter';
import { cerebrasAdapter } from './cerebras-adapter';
import { ai21Adapter } from './ai21-adapter';
import { deepinfraAdapter } from './deepinfra-adapter';
import { novitaAdapter } from './novita-adapter';
import { hyperbolicAdapter } from './hyperbolic-adapter';
import { sambanovaAdapter } from './sambanova-adapter';
import { lambdalabsAdapter } from './lambdalabs-adapter';
import { leptonAdapter } from './lepton-adapter';
import { inferencenetAdapter } from './inferencenet-adapter';
import { nvidiaAdapter } from './nvidia-adapter';
import { cloudflareAdapter } from './cloudflare-adapter';
import { nebiusAdapter } from './nebius-adapter';
import { replicateAdapter } from './replicate-adapter';
import { featherlessAdapter } from './featherless-adapter';
import { huggingfaceAdapter } from './huggingface-adapter';
import { yiAdapter } from './yi-adapter';
import { zhipuAdapter } from './zhipu-adapter';
import { upstageAdapter } from './upstage-adapter';
import { moonshotAdapter } from './moonshot-adapter';
import { writerAdapter } from './writer-adapter';
import { qwenAdapter } from './qwen-adapter';
import { minimaxAdapter } from './minimax-adapter';
import { doubaoAdapter } from './doubao-adapter';
import { hunyuanAdapter } from './hunyuan-adapter';
import { baichuanAdapter } from './baichuan-adapter';
import { siliconflowAdapter } from './siliconflow-adapter';
import { stepfunAdapter } from './stepfun-adapter';
import { baiduAdapter } from './baidu-adapter';
import { klusterAdapter } from './kluster-adapter';
import { friendliAdapter } from './friendli-adapter';
import { llamaapiAdapter } from './llamaapi-adapter';
import { rekaAdapter } from './reka-adapter';
import { maritacaAdapter } from './maritaca-adapter';
import { scalewayAdapter } from './scaleway-adapter';
import { nscaleAdapter } from './nscale-adapter';
import { aimlapiAdapter } from './aimlapi-adapter';
import { bedrockAdapter } from './bedrock-adapter';
import { alephAlphaAdapter } from './alephalpha-adapter';
import { sarvamAdapter } from './sarvam-adapter';
import { chutesAdapter } from './chutes-adapter';
import { krutrimAdapter } from './krutrim-adapter';
import { digitaloceanAdapter } from './digitalocean-adapter';
import { ovhcloudAdapter } from './ovhcloud-adapter';
import { telnyxAdapter } from './telnyx-adapter';
import { vultrAdapter } from './vultr-adapter';
import { ai71Adapter } from './ai71-adapter';
import { gcoreAdapter } from './gcore-adapter';
import { crusoeAdapter } from './crusoe-adapter';
import { databricksAdapter } from './databricks-adapter';
import { gradientAdapter } from './gradient-adapter';
import { basetenAdapter } from './baseten-adapter';
import { watsonxAdapter } from './watsonx-adapter';
import { snowflakeAdapter } from './snowflake-adapter';
import { neetsAdapter } from './neets-adapter';
import { runpodAdapter } from './runpod-adapter';
import { predibaseAdapter } from './predibase-adapter';
import { vertexaiAdapter } from './vertexai-adapter';
import { sparkAdapter } from './spark-adapter';
import { ionetAdapter } from './ionet-adapter';
import { ociAdapter } from './oci-adapter';
import { gigachatAdapter } from './gigachat-adapter';
import { githubAdapter } from './github-adapter';
import { parasailAdapter } from './parasail-adapter';
import { openpipeAdapter } from './openpipe-adapter';
import { corcelAdapter } from './corcel-adapter';
import { inceptionAdapter } from './inception-adapter';
import { liquidAdapter } from './liquid-adapter';
import { zyphraAdapter } from './zyphra-adapter';
import { akashAdapter } from './akash-adapter';
import { arceeAdapter } from './arcee-adapter';
import { centmlAdapter } from './centml-adapter';
import { veniceAdapter } from './venice-adapter';
import { inferlessAdapter } from './inferless-adapter';
import { codestralAdapter } from './codestral-adapter';
import { fluidstackAdapter } from './fluidstack-adapter';
import { monsterapiAdapter } from './monsterapi-adapter';
import { coreweaveAdapter } from './coreweave-adapter';
import { premAdapter } from './prem-adapter';
import { clarifaiAdapter } from './clarifai-adapter';
import { sensenovaAdapter } from './sensenova-adapter';
import { ai360Adapter } from './ai360-adapter';
import { naverAdapter } from './naver-adapter';
import { inflectionAdapter } from './inflection-adapter';
import { yandexAdapter } from './yandex-adapter';
import { falAdapter } from './fal-adapter';
import { ionosAdapter } from './ionos-adapter';
import { anyscaleAdapter } from './anyscale-adapter';
import { nousresearchAdapter } from './nousresearch-adapter';
import { metaAdapter } from './meta-adapter';
import { glhfAdapter } from './glhf-adapter';
import { sakuraAdapter } from './sakura-adapter';
import { textsynthAdapter } from './textsynth-adapter';
import { heuristAdapter } from './heurist-adapter';
import { nearaiAdapter } from './nearai-adapter';
import { netmindAdapter } from './netmind-adapter';
import { hyperstackAdapter } from './hyperstack-adapter';
import { gmiAdapter } from './gmi-adapter';
import { internlmAdapter } from './internlm-adapter';
import { targonAdapter } from './targon-adapter';
import { skyworkAdapter } from './skywork-adapter';
import { infermaticAdapter } from './infermatic-adapter';
import { mancerAdapter } from './mancer-adapter';
import { rhymesAdapter } from './rhymes-adapter';
import { primeintellectAdapter } from './primeintellect-adapter';
import { exaoneAdapter } from './exaone-adapter';
import { mimoAdapter } from './mimo-adapter';
import { laminiAdapter } from './lamini-adapter';
import { intelAdapter } from './intel-adapter';
import { h2oAdapter } from './h2o-adapter';
import { g42Adapter } from './g42-adapter';
import { tensorwaveAdapter } from './tensorwave-adapter';
import { recursalAdapter } from './recursal-adapter';
import { voyageAdapter } from './voyage-adapter';
import { nomicAdapter } from './nomic-adapter';
import { jinaAdapter } from './jina-adapter';
import { tenstorrentAdapter } from './tenstorrent-adapter';
import { mixedbreadAdapter } from './mixedbread-adapter';
import { stabilityAdapter } from './stability-adapter';
import { octoaiAdapter } from './octoai-adapter';
import { ai2Adapter } from './ai2-adapter';
import { lightonAdapter } from './lighton-adapter';
import { modularAdapter } from './modular-adapter';
import { infercomAdapter } from './infercom-adapter';

/**
 * Provider adapter registry.
 * Adapters are registered here and looked up by provider type.
 */
const adapters = new Map<ProviderType, ProviderAdapter>();

// Register built-in adapters
adapters.set('openai', openaiAdapter);
adapters.set('anthropic', anthropicAdapter);
adapters.set('google', googleAdapter);
adapters.set('deepseek', deepseekAdapter);
adapters.set('openrouter', openrouterAdapter);
adapters.set('mistral', mistralAdapter);
adapters.set('azure', azureAdapter);
adapters.set('xai', xaiAdapter);
adapters.set('cohere', cohereAdapter);
adapters.set('groq', groqAdapter);
adapters.set('together', togetherAdapter);
adapters.set('fireworks', fireworksAdapter);
adapters.set('perplexity', perplexityAdapter);
adapters.set('cerebras', cerebrasAdapter);
adapters.set('ai21', ai21Adapter);
adapters.set('deepinfra', deepinfraAdapter);
adapters.set('novita', novitaAdapter);
adapters.set('hyperbolic', hyperbolicAdapter);
adapters.set('sambanova', sambanovaAdapter);
adapters.set('lambdalabs', lambdalabsAdapter);
adapters.set('lepton', leptonAdapter);
adapters.set('inferencenet', inferencenetAdapter);
adapters.set('nvidia', nvidiaAdapter);
adapters.set('cloudflare', cloudflareAdapter);
adapters.set('nebius', nebiusAdapter);
adapters.set('replicate', replicateAdapter);
adapters.set('featherless', featherlessAdapter);
adapters.set('huggingface', huggingfaceAdapter);
adapters.set('yi', yiAdapter);
adapters.set('zhipu', zhipuAdapter);
adapters.set('upstage', upstageAdapter);
adapters.set('moonshot', moonshotAdapter);
adapters.set('writer', writerAdapter);
adapters.set('qwen', qwenAdapter);
adapters.set('minimax', minimaxAdapter);
adapters.set('doubao', doubaoAdapter);
adapters.set('hunyuan', hunyuanAdapter);
adapters.set('baichuan', baichuanAdapter);
adapters.set('siliconflow', siliconflowAdapter);
adapters.set('stepfun', stepfunAdapter);
adapters.set('baidu', baiduAdapter);
adapters.set('kluster', klusterAdapter);
adapters.set('friendli', friendliAdapter);
adapters.set('llamaapi', llamaapiAdapter);
adapters.set('reka', rekaAdapter);
adapters.set('maritaca', maritacaAdapter);
adapters.set('scaleway', scalewayAdapter);
adapters.set('nscale', nscaleAdapter);
adapters.set('aimlapi', aimlapiAdapter);
adapters.set('bedrock', bedrockAdapter);
adapters.set('alephalpha', alephAlphaAdapter);
adapters.set('sarvam', sarvamAdapter);
adapters.set('chutes', chutesAdapter);
adapters.set('krutrim', krutrimAdapter);
adapters.set('digitalocean', digitaloceanAdapter);
adapters.set('ovhcloud', ovhcloudAdapter);
adapters.set('telnyx', telnyxAdapter);
adapters.set('vultr', vultrAdapter);
adapters.set('ai71', ai71Adapter);
adapters.set('gcore', gcoreAdapter);
adapters.set('crusoe', crusoeAdapter);
adapters.set('databricks', databricksAdapter);
adapters.set('gradient', gradientAdapter);
adapters.set('baseten', basetenAdapter);
adapters.set('watsonx', watsonxAdapter);
adapters.set('snowflake', snowflakeAdapter);
adapters.set('neets', neetsAdapter);
adapters.set('runpod', runpodAdapter);
adapters.set('predibase', predibaseAdapter);
adapters.set('vertexai', vertexaiAdapter);
adapters.set('spark', sparkAdapter);
adapters.set('ionet', ionetAdapter);
adapters.set('oci', ociAdapter);
adapters.set('gigachat', gigachatAdapter);
adapters.set('github', githubAdapter);
adapters.set('parasail', parasailAdapter);
adapters.set('openpipe', openpipeAdapter);
adapters.set('corcel', corcelAdapter);
adapters.set('inception', inceptionAdapter);
adapters.set('liquid', liquidAdapter);
adapters.set('zyphra', zyphraAdapter);
adapters.set('akash', akashAdapter);
adapters.set('arcee', arceeAdapter);
adapters.set('centml', centmlAdapter);
adapters.set('venice', veniceAdapter);
adapters.set('inferless', inferlessAdapter);
adapters.set('codestral', codestralAdapter);
adapters.set('fluidstack', fluidstackAdapter);
adapters.set('monsterapi', monsterapiAdapter);
adapters.set('coreweave', coreweaveAdapter);
adapters.set('prem', premAdapter);
adapters.set('clarifai', clarifaiAdapter);
adapters.set('sensenova', sensenovaAdapter);
adapters.set('ai360', ai360Adapter);
adapters.set('naver', naverAdapter);
adapters.set('inflection', inflectionAdapter);
adapters.set('yandex', yandexAdapter);
adapters.set('fal', falAdapter);
adapters.set('ionos', ionosAdapter);
adapters.set('anyscale', anyscaleAdapter);
adapters.set('nousresearch', nousresearchAdapter);
adapters.set('meta', metaAdapter);
adapters.set('glhf', glhfAdapter);
adapters.set('sakura', sakuraAdapter);
adapters.set('textsynth', textsynthAdapter);
adapters.set('heurist', heuristAdapter);
adapters.set('nearai', nearaiAdapter);
adapters.set('netmind', netmindAdapter);
adapters.set('hyperstack', hyperstackAdapter);
adapters.set('gmi', gmiAdapter);
adapters.set('internlm', internlmAdapter);
adapters.set('targon', targonAdapter);
adapters.set('skywork', skyworkAdapter);
adapters.set('infermatic', infermaticAdapter);
adapters.set('mancer', mancerAdapter);
adapters.set('rhymes', rhymesAdapter);
adapters.set('primeintellect', primeintellectAdapter);
adapters.set('exaone', exaoneAdapter);
adapters.set('mimo', mimoAdapter);
adapters.set('lamini', laminiAdapter);
adapters.set('intel', intelAdapter);
adapters.set('h2o', h2oAdapter);
adapters.set('g42', g42Adapter);
adapters.set('tensorwave', tensorwaveAdapter);
adapters.set('recursal', recursalAdapter);
adapters.set('voyage', voyageAdapter);
adapters.set('nomic', nomicAdapter);
adapters.set('jina', jinaAdapter);
adapters.set('tenstorrent', tenstorrentAdapter);
adapters.set('mixedbread', mixedbreadAdapter);
adapters.set('stability', stabilityAdapter);
adapters.set('octoai', octoaiAdapter);
adapters.set('ai2', ai2Adapter);
adapters.set('lighton', lightonAdapter);
adapters.set('modular', modularAdapter);
adapters.set('infercom', infercomAdapter);

export function registerAdapter(adapter: ProviderAdapter) {
  adapters.set(adapter.type, adapter);
}

export function getAdapter(type: ProviderType): ProviderAdapter {
  const adapter = adapters.get(type);
  if (!adapter) {
    throw new Error(`No adapter registered for provider: ${type}`);
  }
  return adapter;
}

export function getRegisteredProviders(): ProviderType[] {
  return Array.from(adapters.keys());
}
