import type { ProviderType } from '@/types';

/**
 * Adapter interface for provider usage APIs.
 * Each provider (OpenAI, Anthropic, etc.) implements this interface.
 */
export interface ProviderAdapter {
  readonly type: ProviderType;

  /**
   * Validates the API key by making a test request.
   * Returns true if valid, throws with error message if not.
   */
  validateKey(apiKey: string): Promise<boolean>;

  /**
   * Fetches usage data for a date range.
   */
  fetchUsage(
    apiKey: string,
    startDate: Date,
    endDate: Date
  ): Promise<NormalizedUsageRecord[]>;
}

export interface NormalizedUsageRecord {
  date: string; // YYYY-MM-DD
  model: string;
  inputTokens: number;
  outputTokens: number;
  requests: number;
  costUsd: number;
  rawData?: Record<string, unknown>;
}

export interface ProviderMeta {
  type: ProviderType;
  name: string;
  description: string;
  keyPrefix: string;
  keyPlaceholder: string;
  helpUrl: string;
  color: string;
}

/**
 * Registry of supported providers with their metadata.
 */
export const PROVIDER_META: Record<ProviderType, ProviderMeta> = {
  openai: {
    type: 'openai',
    name: 'OpenAI',
    description: 'GPT-4o, GPT-4o-mini, o1, DALL-E, Whisper',
    keyPrefix: 'sk-',
    keyPlaceholder: 'sk-...',
    helpUrl: 'https://platform.openai.com/api-keys',
    color: '#10A37F',
  },
  anthropic: {
    type: 'anthropic',
    name: 'Anthropic',
    description: 'Claude Opus, Sonnet, Haiku',
    keyPrefix: 'sk-ant-',
    keyPlaceholder: 'sk-ant-admin-...',
    helpUrl: 'https://console.anthropic.com/settings/keys',
    color: '#D4A574',
  },
  google: {
    type: 'google',
    name: 'Google AI',
    description: 'Gemini 2.0 Flash, Gemini 2.0 Pro, Gemini 1.5',
    keyPrefix: 'AI',
    keyPlaceholder: 'AIza...',
    helpUrl: 'https://aistudio.google.com/app/apikey',
    color: '#4285F4',
  },
  deepseek: {
    type: 'deepseek',
    name: 'DeepSeek',
    description: 'DeepSeek V3, DeepSeek R1, Coder',
    keyPrefix: 'sk-',
    keyPlaceholder: 'sk-...',
    helpUrl: 'https://platform.deepseek.com/api_keys',
    color: '#0066FF',
  },
  openrouter: {
    type: 'openrouter',
    name: 'OpenRouter',
    description: '500+ models: Claude, GPT, Gemini, Llama, Mistral & more',
    keyPrefix: 'sk-or-',
    keyPlaceholder: 'sk-or-v1-...',
    helpUrl: 'https://openrouter.ai/settings/keys',
    color: '#6366F1',
  },
  mistral: {
    type: 'mistral',
    name: 'Mistral AI',
    description: 'Mistral Large, Mistral Small, Codestral, Pixtral',
    keyPrefix: '',
    keyPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    helpUrl: 'https://console.mistral.ai/api-keys',
    color: '#FF7000',
  },
  azure: {
    type: 'azure',
    name: 'Azure OpenAI',
    description: 'GPT-4o, GPT-4, o1 via Azure OpenAI Service',
    keyPrefix: 'https://',
    keyPlaceholder: 'https://my-resource.openai.azure.com/::my-azure-api-key',
    helpUrl: 'https://portal.azure.com/#view/Microsoft_Azure_ProjectOxford/CognitiveServicesHub/~/OpenAI',
    color: '#0078D4',
  },
  xai: {
    type: 'xai',
    name: 'xAI (Grok)',
    description: 'Grok 3, Grok 3 Fast, Grok 3 Mini',
    keyPrefix: 'xai-',
    keyPlaceholder: 'xai-...',
    helpUrl: 'https://console.x.ai/settings/api-keys',
    color: '#1DA1F2',
  },
  cohere: {
    type: 'cohere',
    name: 'Cohere',
    description: 'Command R+, Command R, Embed, Rerank',
    keyPrefix: '',
    keyPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    helpUrl: 'https://dashboard.cohere.com/api-keys',
    color: '#39594D',
  },
  groq: {
    type: 'groq',
    name: 'Groq',
    description: 'Llama 4, Llama 3.3 70B, Gemma 2, Mixtral — ultra-fast inference',
    keyPrefix: 'gsk_',
    keyPlaceholder: 'gsk_...',
    helpUrl: 'https://console.groq.com/keys',
    color: '#F55036',
  },
  together: {
    type: 'together',
    name: 'Together AI',
    description: 'Llama 4, DeepSeek R1/V3, Qwen 2.5, Mixtral — open-source models',
    keyPrefix: '',
    keyPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    helpUrl: 'https://api.together.ai/settings/api-keys',
    color: '#0F6FFF',
  },
  fireworks: {
    type: 'fireworks',
    name: 'Fireworks AI',
    description: 'Llama 4, DeepSeek R1/V3, Qwen 2.5, Mixtral — fast open-source inference',
    keyPrefix: 'fw_',
    keyPlaceholder: 'fw_...',
    helpUrl: 'https://fireworks.ai/settings/users/api-keys',
    color: '#FF6B35',
  },
  perplexity: {
    type: 'perplexity',
    name: 'Perplexity AI',
    description: 'Sonar, Sonar Pro, Sonar Reasoning — search-augmented models',
    keyPrefix: 'pplx-',
    keyPlaceholder: 'pplx-...',
    helpUrl: 'https://www.perplexity.ai/settings/api',
    color: '#20B2AA',
  },
  cerebras: {
    type: 'cerebras',
    name: 'Cerebras',
    description: 'Llama 3.1/3.3, Qwen 3, DeepSeek R1 — ultra-fast inference on Cerebras hardware',
    keyPrefix: 'csk-',
    keyPlaceholder: 'csk-...',
    helpUrl: 'https://cloud.cerebras.ai/platform',
    color: '#F15A24',
  },
  ai21: {
    type: 'ai21',
    name: 'AI21 Labs',
    description: 'Jamba 1.5/1.6 Mini and Large — long-context SSM-Transformer hybrid models',
    keyPrefix: '',
    keyPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    helpUrl: 'https://studio.ai21.com/account/api-key',
    color: '#6C47FF',
  },
  deepinfra: {
    type: 'deepinfra',
    name: 'DeepInfra',
    description: 'Llama 4, DeepSeek R1/V3, Qwen, Phi-4, Mixtral — low-cost open-source inference',
    keyPrefix: '',
    keyPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    helpUrl: 'https://deepinfra.com/dash/api_keys',
    color: '#6B21A8',
  },
  novita: {
    type: 'novita',
    name: 'Novita AI',
    description: 'Llama 3.1/3.3, DeepSeek R1/V3, Qwen 2.5, Mistral — cheap open-source inference',
    keyPrefix: '',
    keyPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    helpUrl: 'https://novita.ai/settings/key-management',
    color: '#7C3AED',
  },
  hyperbolic: {
    type: 'hyperbolic',
    name: 'Hyperbolic',
    description: 'Llama 4, DeepSeek R1/V3, Qwen 2.5, Mistral — low-latency open-source inference',
    keyPrefix: '',
    keyPlaceholder: 'eyJhbGc...',
    helpUrl: 'https://app.hyperbolic.xyz/settings',
    color: '#0EA5E9',
  },
  sambanova: {
    type: 'sambanova',
    name: 'SambaNova Cloud',
    description: 'Llama 3.1/3.3/4, DeepSeek R1/V3, Qwen 2.5 — ultra-fast inference on custom hardware',
    keyPrefix: '',
    keyPlaceholder: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
    helpUrl: 'https://cloud.sambanova.ai/apis',
    color: '#FF6B35',
  },
  lambdalabs: {
    type: 'lambdalabs',
    name: 'Lambda Labs',
    description: 'Llama 3.1/3.3, Hermes 3, Qwen 2.5, Liquid LFM — on-demand GPU cloud inference',
    keyPrefix: '',
    keyPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    helpUrl: 'https://cloud.lambdalabs.com/api-keys',
    color: '#7B2D8B',
  },
  lepton: {
    type: 'lepton',
    name: 'Lepton AI',
    description: 'Llama 3.1/3, Mistral 7B, Mixtral 8x7B, Qwen 2.5 — low-latency inference API',
    keyPrefix: '',
    keyPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    helpUrl: 'https://dashboard.lepton.ai/',
    color: '#6366F1',
  },
  inferencenet: {
    type: 'inferencenet',
    name: 'Inference.net',
    description: 'Llama 3.3 70B, DeepSeek R1/V3, Qwen 2.5, Mistral — NVIDIA H100-powered inference',
    keyPrefix: '',
    keyPlaceholder: 'inf-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    helpUrl: 'https://app.inference.net/keys',
    color: '#10B981',
  },
  nvidia: {
    type: 'nvidia',
    name: 'NVIDIA NIM',
    description: 'Llama 3.3 70B, Nemotron, Mistral, DeepSeek R1 — NVIDIA-hosted inference APIs',
    keyPrefix: 'nvapi-',
    keyPlaceholder: 'nvapi-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    helpUrl: 'https://build.nvidia.com',
    color: '#76B900',
  },
  cloudflare: {
    type: 'cloudflare',
    name: 'Cloudflare Workers AI',
    description: 'Llama 3.3 70B, Llama 3.2, Mistral 7B, Gemma — edge inference with global network',
    keyPrefix: '',
    keyPlaceholder: 'accountId::apiToken',
    helpUrl: 'https://dash.cloudflare.com/profile/api-tokens',
    color: '#F38020',
  },
  nebius: {
    type: 'nebius',
    name: 'Nebius AI',
    description: 'Llama 3.3 70B, DeepSeek R1/V3, Qwen 2.5 72B, Mistral Nemo — European-first cloud inference',
    keyPrefix: '',
    keyPlaceholder: 'eyJhbGci...',
    helpUrl: 'https://studio.nebius.ai',
    color: '#5B4CF5',
  },
  replicate: {
    type: 'replicate',
    name: 'Replicate',
    description: 'Llama 3.3 70B, DeepSeek R1, Mixtral, Gemma 2, Qwen 2.5 — deploy and run any open-source model',
    keyPrefix: 'r8_',
    keyPlaceholder: 'r8_...',
    helpUrl: 'https://replicate.com/account/api-tokens',
    color: '#000000',
  },
  featherless: {
    type: 'featherless',
    name: 'Featherless.ai',
    description: 'Llama 3.3 70B, DeepSeek R1, Qwen 2.5, Phi-4 — 3,000+ open-source models, serverless, no GPU setup',
    keyPrefix: '',
    keyPlaceholder: 'your-featherless-api-key',
    helpUrl: 'https://featherless.ai/account',
    color: '#7C3AED',
  },
  huggingface: {
    type: 'huggingface',
    name: 'HuggingFace',
    description: 'Llama 3.3 70B, Mistral 7B, Qwen 2.5, DeepSeek R1, Gemma 2 — serverless inference on 100,000+ open-source models',
    keyPrefix: 'hf_',
    keyPlaceholder: 'hf_...',
    helpUrl: 'https://huggingface.co/settings/tokens',
    color: '#FF9D00',
  },
  yi: {
    type: 'yi',
    name: '01.AI',
    description: 'Yi-Lightning, Yi-Large, Yi-Medium, Yi-Spark — 01.AI Yi models, OpenAI-compatible, ultra-low cost',
    keyPrefix: '',
    keyPlaceholder: 'your-01ai-api-key',
    helpUrl: 'https://platform.lingyiwanwu.com/apikeys',
    color: '#1A73E8',
  },
  zhipu: {
    type: 'zhipu',
    name: 'Zhipu AI',
    description: 'GLM-4-Plus, GLM-4, GLM-4-Long, GLM-4-Flash, GLM-4-Air — ChatGLM models, OpenAI-compatible, Chinese AI',
    keyPrefix: '',
    keyPlaceholder: 'your-zhipu-api-key',
    helpUrl: 'https://open.bigmodel.cn/usercenter/apikeys',
    color: '#4E6EF2',
  },
  upstage: {
    type: 'upstage',
    name: 'Upstage',
    description: 'Solar Pro, Solar Mini — Korean AI company, top-ranked open LLMs on OpenLLM leaderboard',
    keyPrefix: 'up_',
    keyPlaceholder: 'up_...',
    helpUrl: 'https://console.upstage.ai/api-keys',
    color: '#FF6B2B',
  },
  moonshot: {
    type: 'moonshot',
    name: 'Moonshot AI',
    description: 'moonshot-v1-8k, moonshot-v1-32k, moonshot-v1-128k — Kimi models, OpenAI-compatible, long-context Chinese AI',
    keyPrefix: 'sk-',
    keyPlaceholder: 'sk-...',
    helpUrl: 'https://platform.moonshot.cn/user/api-keys',
    color: '#1A73E8',
  },
  writer: {
    type: 'writer',
    name: 'Writer',
    description: 'Palmyra X 004, Palmyra Med 70B, Palmyra Fin 70B — enterprise AI, domain-specialized models, OpenAI-compatible',
    keyPrefix: '',
    keyPlaceholder: 'your-writer-api-key',
    helpUrl: 'https://app.writer.com/aistudio/organization/apps',
    color: '#6C47FF',
  },
  qwen: {
    type: 'qwen',
    name: 'Alibaba Cloud (Qwen)',
    description: 'Qwen-Max, Qwen-Plus, Qwen-Turbo, Qwen3 — Alibaba Cloud DashScope, OpenAI-compatible, multilingual AI',
    keyPrefix: 'sk-',
    keyPlaceholder: 'sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    helpUrl: 'https://bailian.console.aliyun.com/apiKey',
    color: '#FF6A00',
  },
  minimax: {
    type: 'minimax',
    name: 'MiniMax',
    description: 'MiniMax-Text-01, abab6.5s-chat, abab5.5s-chat — OpenAI-compatible, 1M context window Chinese AI',
    keyPrefix: '',
    keyPlaceholder: 'your-minimax-api-key',
    helpUrl: 'https://platform.minimaxi.chat/user-center/basic-information/interface-key',
    color: '#0066FF',
  },
  doubao: {
    type: 'doubao',
    name: 'ByteDance (Doubao)',
    description: 'Doubao-Pro-32k, Doubao-Lite-32k, Doubao-1.5-Pro — OpenAI-compatible, ultra-low cost, TikTok parent company AI',
    keyPrefix: '',
    keyPlaceholder: 'your-volcengine-ark-api-key',
    helpUrl: 'https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey',
    color: '#E02B2B',
  },
  hunyuan: {
    type: 'hunyuan',
    name: 'Tencent Hunyuan',
    description: 'Hunyuan-Pro, Hunyuan-Turbo, Hunyuan-Standard — OpenAI-compatible, Tencent Cloud AI with 256K context',
    keyPrefix: '',
    keyPlaceholder: 'your-hunyuan-api-key',
    helpUrl: 'https://console.cloud.tencent.com/hunyuan/api-key',
    color: '#00A3FF',
  },
  baichuan: {
    type: 'baichuan',
    name: 'Baichuan AI',
    description: 'Baichuan4, Baichuan4-Turbo, Baichuan4-Air — OpenAI-compatible, Chinese LLMs with strong bilingual performance',
    keyPrefix: '',
    keyPlaceholder: 'your-baichuan-api-key',
    helpUrl: 'https://platform.baichuan-ai.com/console/apikey',
    color: '#5B8FF9',
  },
  siliconflow: {
    type: 'siliconflow',
    name: 'SiliconFlow',
    description: 'SiliconCloud — DeepSeek-V3, Qwen2.5, Llama 3.3 and 300+ open-source models at ultra-low cost',
    keyPrefix: '',
    keyPlaceholder: 'your-siliconflow-api-key',
    helpUrl: 'https://cloud.siliconflow.cn/account/ak',
    color: '#00B4D8',
  },
  stepfun: {
    type: 'stepfun',
    name: 'Stepfun',
    description: 'step-2 reasoning, step-1-32k, step-1-flash — Chinese AI with OpenAI-compatible API',
    keyPrefix: '',
    keyPlaceholder: 'your-stepfun-api-key',
    helpUrl: 'https://platform.stepfun.com/apikeys',
    color: '#FF6F61',
  },
  baidu: {
    type: 'baidu',
    name: 'Baidu AI Cloud (ERNIE)',
    description: 'ERNIE-4.0, ERNIE-3.5, ERNIE-Speed, ERNIE-Lite — Baidu Qianfan, OpenAI-compatible, Chinese AI',
    keyPrefix: '',
    keyPlaceholder: 'your-baidu-qianfan-api-key',
    helpUrl: 'https://console.bce.baidu.com/qianfan/apikey/list',
    color: '#2932E1',
  },
  kluster: {
    type: 'kluster',
    name: 'Kluster AI',
    description: 'Llama 3.3/4, DeepSeek R1/V3, Qwen 2.5/3 — European GPU cloud, OpenAI-compatible',
    keyPrefix: '',
    keyPlaceholder: 'your-kluster-api-key',
    helpUrl: 'https://platform.kluster.ai/account/api-keys',
    color: '#7C3AED',
  },
  friendli: {
    type: 'friendli',
    name: 'Friendli AI',
    description: 'Llama 3.3/3.1, DeepSeek R1/V3, Qwen 2.5, Mixtral — Korean serverless inference, OpenAI-compatible',
    keyPrefix: '',
    keyPlaceholder: 'your-friendli-personal-access-token',
    helpUrl: 'https://suite.friendli.ai/user/personal-access-tokens',
    color: '#6366F1',
  },
  llamaapi: {
    type: 'llamaapi',
    name: 'Llama API',
    description: 'Llama 4 Scout/Maverick, Llama 3.3 70B, Llama 3.1 405B/70B/8B, Llama 3.2 Vision — Meta\'s official inference API, OpenAI-compatible',
    keyPrefix: '',
    keyPlaceholder: 'your-llama-api-key',
    helpUrl: 'https://llama.developer.meta.com/docs/overview',
    color: '#0866FF',
  },
  reka: {
    type: 'reka',
    name: 'Reka AI',
    description: 'reka-core, reka-flash, reka-edge — multimodal text+vision models from Reka AI, OpenAI-compatible',
    keyPrefix: '',
    keyPlaceholder: 'your-reka-api-key',
    helpUrl: 'https://platform.reka.ai/settings/api-keys',
    color: '#7C3AED',
  },
  maritaca: {
    type: 'maritaca',
    name: 'Maritaca AI',
    description: 'Sabiá-3, Sabiá-3 Small — Portuguese-optimized LLMs from Maritaca AI (Brazil)',
    keyPrefix: '',
    keyPlaceholder: 'your-maritaca-api-key',
    helpUrl: 'https://plataforma.maritaca.ai/',
    color: '#009C3B',
  },
  scaleway: {
    type: 'scaleway',
    name: 'Scaleway',
    description: 'Llama 3.3 70B, Mistral Nemo, DeepSeek R1 — open-source LLMs hosted on French GDPR-native infrastructure',
    keyPrefix: 'scw',
    keyPlaceholder: 'scw-your-iam-secret-key',
    helpUrl: 'https://console.scaleway.com/iam/api-keys',
    color: '#4F0599',
  },
  nscale: {
    type: 'nscale',
    name: 'Nscale',
    description: 'Llama 3.3 70B, DeepSeek R1, Mistral 7B — open-source LLMs on UK AI infrastructure with competitive European pricing',
    keyPrefix: '',
    keyPlaceholder: 'your-nscale-api-key',
    helpUrl: 'https://console.nscale.com/settings',
    color: '#1E3A5F',
  },
  aimlapi: {
    type: 'aimlapi',
    name: 'AI/ML API',
    description: 'Llama 4 Scout/Maverick, DeepSeek R1/V3, Qwen 2.5 72B — 200+ models via a single OpenAI-compatible API key',
    keyPrefix: '',
    keyPlaceholder: 'your-aimlapi-key',
    helpUrl: 'https://aimlapi.com/app/keys',
    color: '#6366F1',
  },
  bedrock: {
    type: 'bedrock',
    name: 'AWS Bedrock',
    description: 'Amazon Nova, Titan, Claude, Llama 3.3, Mistral — foundation models in your AWS account',
    keyPrefix: '',
    keyPlaceholder: 'us-east-1::AKIAIOSFODNN7EXAMPLE::wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY',
    helpUrl: 'https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html',
    color: '#FF9900',
  },
  alephalpha: {
    type: 'alephalpha',
    name: 'Aleph Alpha',
    description: 'Luminous Base, Extended, Supreme, Pharia — European sovereign AI from Germany',
    keyPrefix: '',
    keyPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    helpUrl: 'https://app.aleph-alpha.com/profile',
    color: '#1A1A2E',
  },
  sarvam: {
    type: 'sarvam',
    name: 'Sarvam AI',
    description: 'Sarvam-M, Sarvam-1, Sarvam-2B — Indian multilingual LLMs with native support for Hindi, Bengali, Tamil, Telugu, and 6 more Indic languages',
    keyPrefix: '',
    keyPlaceholder: 'your-sarvam-api-key',
    helpUrl: 'https://dashboard.sarvam.ai',
    color: '#FF6B2B',
  },
  chutes: {
    type: 'chutes',
    name: 'Chutes AI',
    description: 'Llama 4 Scout, Llama 3.3 70B, DeepSeek R1/V3, Qwen 2.5 72B, Mistral 7B — permissionless community inference network, Llama 3.1 8B and Mistral 7B from $0.04/1M tokens',
    keyPrefix: '',
    keyPlaceholder: 'your-chutes-api-key',
    helpUrl: 'https://chutes.ai/settings',
    color: '#6366F1',
  },
  krutrim: {
    type: 'krutrim',
    name: 'Krutrim',
    description: 'Krutrim-2, Krutrim-Spectre-v2 — India\'s first AI unicorn LLM platform by Ola founder Bhavish Aggarwal, bilingual Hindi/English with competitive pricing',
    keyPrefix: '',
    keyPlaceholder: 'your-krutrim-api-key',
    helpUrl: 'https://cloud.olakrutrim.com/console',
    color: '#FF6600',
  },
  digitalocean: {
    type: 'digitalocean',
    name: 'DigitalOcean',
    description: 'Llama 4 Maverick, Llama 3.3 70B, DeepSeek V3.2, Qwen3-32B — hosted open-source models on DigitalOcean AI Inference, developer-friendly cloud with 32 global data centers',
    keyPrefix: '',
    keyPlaceholder: 'your-digitalocean-model-access-key',
    helpUrl: 'https://cloud.digitalocean.com/account/api/tokens',
    color: '#0080FF',
  },
  ovhcloud: {
    type: 'ovhcloud',
    name: 'OVHcloud AI',
    description: 'Llama 3.3 70B, Mistral 7B, Mixtral 8x7B, Qwen 2.5 72B — open-source LLM inference on Europe\'s largest cloud, GDPR-native French data centers, Mistral 7B from $0.04/1M tokens',
    keyPrefix: '',
    keyPlaceholder: 'your-ovhcloud-ai-endpoints-token',
    helpUrl: 'https://endpoints.ai.cloud.ovh.net',
    color: '#00B4E6',
  },
  telnyx: {
    type: 'telnyx',
    name: 'Telnyx AI',
    description: 'Llama 3.3 70B, Llama 3.1 405B, Mistral 7B, Mixtral 8x7B — LLM inference on carrier-grade global infrastructure from Telnyx, telecom-grade reliability with competitive pricing',
    keyPrefix: 'KEY_',
    keyPlaceholder: 'KEY_your-telnyx-api-key',
    helpUrl: 'https://portal.telnyx.com',
    color: '#00C4B4',
  },
  vultr: {
    type: 'vultr',
    name: 'Vultr Cloud Inference',
    description: 'Llama 3.3 70B, Llama 3.1 70B, Llama 3.1 8B, Mistral 7B, Mixtral 8x7B — cost-competitive LLM inference across 33 global data centers from Vultr, developer-friendly infrastructure cloud',
    keyPrefix: '',
    keyPlaceholder: 'your-vultr-api-key',
    helpUrl: 'https://my.vultr.com/settings/#api',
    color: '#009BDE',
  },
  ai71: {
    type: 'ai71',
    name: 'AI71',
    description: 'Falcon 3 10B, Falcon 3 7B, Falcon 3 3B, Falcon 3 1B, Falcon 2 11B — sovereign AI inference from the UAE by AI71 (Technology Innovation Institute), open-weight Falcon models with symmetric pricing',
    keyPrefix: 'api71-',
    keyPlaceholder: 'api71-your-ai71-api-key',
    helpUrl: 'https://platform.ai71.ai',
    color: '#00A651',
  },
  gcore: {
    type: 'gcore',
    name: 'Gcore',
    description: 'Llama 3.3 70B, Llama 3.1 8B, Mistral 7B, Mixtral 8x7B, DeepSeek R1 — European CDN and cloud provider (Luxembourg) with 165+ global PoPs, OpenAI-compatible LLM inference with EU data residency',
    keyPrefix: '',
    keyPlaceholder: 'your-gcore-api-key',
    helpUrl: 'https://gcore.com/inference',
    color: '#FF6600',
  },
  crusoe: {
    type: 'crusoe',
    name: 'Crusoe Cloud',
    description: 'Llama 3.3 70B, Llama 3.1 405B/70B/8B, DeepSeek R1, Qwen 2.5 72B, Mistral 7B — sustainable AI cloud running on stranded natural gas, cutting carbon emissions by ~63% vs traditional cloud. OpenAI-compatible inference API.',
    keyPrefix: '',
    keyPlaceholder: 'your-crusoe-api-key',
    helpUrl: 'https://docs.crusoe.ai/llm-inference',
    color: '#00B050',
  },
  databricks: {
    type: 'databricks',
    name: 'Databricks',
    description: 'DBRX Instruct (132B MoE), Llama 3.3 70B, Llama 3.1 405B/70B/8B, Mixtral 8x7B, Mistral 7B, Llama 2 70B — Foundation Model APIs from the data lakehouse leader. OpenAI-compatible pay-per-token inference with no workspace required.',
    keyPrefix: '',
    keyPlaceholder: 'your-databricks-personal-access-token',
    helpUrl: 'https://docs.databricks.com/aws/en/machine-learning/foundation-models/',
    color: '#FF3621',
  },
  gradient: {
    type: 'gradient',
    name: 'Gradient AI',
    description: 'Llama 3.3 70B, Llama 3.1 405B/70B/8B, Mistral 7B, CodeLlama 34B, Nous Hermes 2 — the only inference platform where you can fine-tune private models and serve them instantly. OpenAI-compatible serverless inference with built-in LoRA fine-tuning.',
    keyPrefix: '',
    keyPlaceholder: 'your-gradient-api-key',
    helpUrl: 'https://docs.gradient.ai',
    color: '#6B2BD6',
  },
  baseten: {
    type: 'baseten',
    name: 'Baseten',
    description: 'Llama 3.3 70B, Llama 3.1 405B/8B, Mistral 7B/Nemo 12B, Qwen 2.5 72B, DeepSeek R1, Phi-3 Medium 128K — production ML inference platform (a16z-backed) trusted by Tesla, Box, and Calendly. Serve public models and private fine-tuned models on the same OpenAI-compatible endpoint. Symmetric pricing across most models.',
    keyPrefix: '',
    keyPlaceholder: 'your-baseten-api-key',
    helpUrl: 'https://docs.baseten.co',
    color: '#5046E5',
  },
  watsonx: {
    type: 'watsonx',
    name: 'IBM WatsonX',
    description: 'Granite 3.2 8B/2B, Granite 13B/20B, Llama 3.3 70B, Llama 3.1 8B, Mistral Large, Mistral 7B — IBM\'s enterprise AI platform. Includes IBM\'s own Granite models (Apache 2.0, FIPS 140-2 certified infrastructure) and hosted open-weight models on IBM Cloud.',
    keyPrefix: '',
    keyPlaceholder: 'your-ibm-cloud-api-key::your-watsonx-project-id',
    helpUrl: 'https://cloud.ibm.com/apidocs/watsonx-ai',
    color: '#0062FF',
  },
  snowflake: {
    type: 'snowflake',
    name: 'Snowflake Cortex AI',
    description: 'Snowflake Arctic 480B MoE (Apache 2.0), Llama 3.3 70B, Llama 3.1 405B/70B/8B, Mistral Large, Mistral 7B, Mixtral 8x7B — Snowflake\'s managed LLM inference service. Includes Snowflake\'s own Arctic model (enterprise-focused MoE, Apache 2.0) and hosted open-weight models. All models use symmetric pricing. Data cloud from Snowflake ($60B+ valuation, 10,000+ enterprise customers).',
    keyPrefix: '',
    keyPlaceholder: 'your-account-identifier::your-jwt-or-pat-token',
    helpUrl: 'https://docs.snowflake.com/en/user-guide/snowflake-cortex/cortex-llm-rest-api',
    color: '#29B5E8',
  },
  neets: {
    type: 'neets',
    name: 'Neets.ai',
    description: 'Llama 3.3 70B, Llama 3.1 405B/70B/8B, Mixtral 8x22B/8x7B, Mistral 7B, Hermes 3 Llama 3.1 8B — serverless LLM inference with 100% symmetric pricing across all models (input = output). Cheapest Mistral 7B inference at $0.05/1M tokens.',
    keyPrefix: '',
    keyPlaceholder: 'your-neets-api-key',
    helpUrl: 'https://neets.ai/docs',
    color: '#6366F1',
  },
  runpod: {
    type: 'runpod',
    name: 'RunPod',
    description: 'Llama 3.3 70B, Llama 3.1 405B/70B/8B, Mistral 7B, DeepSeek R1, Qwen 2.5 72B, Mixtral 8x7B — GPU cloud serverless inference with pay-per-second billing on H100/A100/L40S clusters. Deploy any open-weight model on bare-metal GPU infrastructure from $0.50/GPU-hour.',
    keyPrefix: '',
    keyPlaceholder: 'your-runpod-api-key',
    helpUrl: 'https://docs.runpod.io/serverless/references/openai-compatibility',
    color: '#6D28D9',
  },
  predibase: {
    type: 'predibase',
    name: 'Predibase',
    description: 'Llama 3.3 70B, Llama 3.1 70B/8B, Mistral 7B, Mixtral 8x7B, DeepSeek R1, Phi-3 Medium 128K, Qwen 2.5 72B — the only inference platform purpose-built for fine-tuned LLMs (LoRA adapters). Symmetric pricing across 6 of 8 models. Cheapest Llama 3.1 8B at $0.20/1M (symmetric).',
    keyPrefix: '',
    keyPlaceholder: 'your-predibase-api-key',
    helpUrl: 'https://docs.predibase.com/api-reference',
    color: '#8B5CF6',
  },
  vertexai: {
    type: 'vertexai',
    name: 'Google Vertex AI',
    description: 'Gemini 2.5 Pro, Gemini 2.5 Flash, Gemini 2.0 Flash, Gemini 1.5 Pro/Flash — Google Cloud\'s enterprise-grade AI platform. SOC2/HIPAA/FedRAMP compliant. Credentials: project_id::location::access_token (generate token with: gcloud auth print-access-token).',
    keyPrefix: '',
    keyPlaceholder: 'my-gcp-project::us-central1::ya29.a0AfH6SMC...',
    helpUrl: 'https://cloud.google.com/vertex-ai/generative-ai/docs/start/quickstarts',
    color: '#4285F4',
  },
  spark: {
    type: 'spark',
    name: 'iFlyTek Spark',
    description: 'Spark Lite, Spark Pro, Spark Pro 128K, Spark Max, Spark Max 32K, Spark 4.0 Ultra, Spark X1 — China\'s speech AI giant enters the LLM race. All 8 models use symmetric pricing (input = output). Spark Lite $0.028/1M is 98.6% cheaper than GPT-4o input.',
    keyPrefix: '',
    keyPlaceholder: 'your-iflytek-spark-api-key',
    helpUrl: 'https://www.xfyun.cn/doc/spark/API.html',
    color: '#0066CC',
  },
  ionet: {
    type: 'ionet',
    name: 'io.net',
    description: 'Llama 3.3 70B, DeepSeek R1, Qwen 2.5 72B, Mistral 7B and more — community-owned decentralized GPU cloud from 100+ countries. Symmetric pricing on most models. Llama 3.1 8B $0.05/1M is 98% cheaper than GPT-4o input.',
    keyPrefix: '',
    keyPlaceholder: 'your-ionet-api-key',
    helpUrl: 'https://docs.io.net/docs/inference-api',
    color: '#6366F1',
  },
  oci: {
    type: 'oci',
    name: 'Oracle Cloud (OCI)',
    description: 'Cohere Command R+, Command R, Meta Llama 3.3 70B, Llama 3.1 405B/70B/8B, Mistral Large 2, Mistral 7B — Oracle Cloud Infrastructure Generative AI. The 4th enterprise hyperscaler. SOC2/HIPAA/FedRAMP/ISO 27001. 95% of Fortune 500 are Oracle customers. Credentials: compartmentId::authToken.',
    keyPrefix: 'ocid1.',
    keyPlaceholder: 'ocid1.compartment.oc1..aaa...::eyJhbGci...',
    helpUrl: 'https://docs.oracle.com/en-us/iaas/api/#/en/generative-ai-inference/20231130/',
    color: '#C74634',
  },
  gigachat: {
    type: 'gigachat',
    name: 'GigaChat (Sberbank)',
    description: 'GigaChat Lite, GigaChat Pro, GigaChat Max, GigaChat 2 — Sberbank\'s sovereign Russian AI. 100M+ users. 100% symmetric pricing across all models. The LLM powering Russia\'s largest bank ecosystem. Supports Russian and 30+ languages. Provide your Authorization Key from developers.sber.ru.',
    keyPrefix: '',
    keyPlaceholder: 'OGYzNDI4ZWEtM2I...',
    helpUrl: 'https://developers.sber.ru/docs/ru/gigachat/api/reference/rest/post-token',
    color: '#21A038',
  },
  github: {
    type: 'github',
    name: 'GitHub Models',
    description: 'Microsoft & GitHub AI model inference: GPT-4o, Llama 3.1, Phi-4, Mistral — 100M+ developers, OpenAI-compatible API',
    keyPrefix: '',
    keyPlaceholder: 'github_pat_11A...',
    helpUrl: 'https://github.com/marketplace/models',
    color: '#24292F',
  },
  parasail: {
    type: 'parasail',
    name: 'Parasail',
    description: 'Global distributed AI inference network — up to 30× cheaper than legacy cloud, no quotas, no lock-ins, Day 0 frontier models',
    keyPrefix: '',
    keyPlaceholder: 'ps-...',
    helpUrl: 'https://docs.parasail.io',
    color: '#6C47FF',
  },
  openpipe: {
    type: 'openpipe',
    name: 'OpenPipe',
    description: 'Fine-tuned model serving platform',
    keyPrefix: 'opk_',
    keyPlaceholder: 'opk_...',
    helpUrl: 'https://openpipe.ai',
    color: '#8B5CF6',
  },
  corcel: {
    type: 'corcel',
    name: 'Corcel',
    description: 'Llama 3.3 70B, Llama 3.1 70B/8B, DeepSeek R1/V3, Qwen 2.5 72B, Mistral 7B — Bittensor-powered decentralized AI inference. Llama 3.1 8B $0.03/1M — ~99% cheaper than GPT-4o. Mistral 7B $0.02/1M — cheapest tracked on LLMeter.',
    keyPrefix: '',
    keyPlaceholder: 'your-corcel-api-key',
    helpUrl: 'https://app.corcel.io/dashboard',
    color: '#5B4CF5',
  },
  inception: {
    type: 'inception',
    name: 'Inception AI',
    description: 'Mercury Coder Small, Mercury Coder Large, Mercury Mini, Mercury 20B — diffusion-based LLMs (non-transformer). First diffusion LLM provider on LLMeter. Mercury Mini $0.04/1M — ultra-fast inference. 100% symmetric pricing on all coding models.',
    keyPrefix: '',
    keyPlaceholder: 'your-inception-api-key',
    helpUrl: 'https://inceptionlabs.ai/dashboard',
    color: '#6366F1',
  },
  liquid: {
    type: 'liquid',
    name: 'Liquid AI',
    description: 'LFM-40B, LFM-7B, LFM-3B, LFM-1B — Liquid Foundation Models (LFMs) based on liquid neural networks (non-transformer). MIT spin-off, $37M raised. LFM-40B rivals models 6× larger. LFM-3B $0.10/$0.10 per 1M — 96% cheaper input than GPT-4o. All 8 models symmetric pricing.',
    keyPrefix: '',
    keyPlaceholder: 'your-liquid-api-key',
    helpUrl: 'https://liquid.ai/dashboard',
    color: '#0EA5E9',
  },
  zyphra: {
    type: 'zyphra',
    name: 'Zyphra',
    description: 'Zamba2-7B, Zamba2-2.7B, Zamba2-1.2B — Mamba SSM (State Space Model) hybrid architecture. Third non-transformer architecture on LLMeter. 6× faster inference than same-sized Transformers, 3× lower memory footprint. Zamba2-7B rivals Llama 3.1 8B at a smaller size. 100% symmetric pricing across all 8 models.',
    keyPrefix: '',
    keyPlaceholder: 'your-zyphra-api-key',
    helpUrl: 'https://www.zyphra.com/api',
    color: '#7C3AED',
  },
  akash: {
    type: 'akash',
    name: 'Akash Network',
    description: 'Llama 3.3 70B, Llama 3.1 8B/405B, DeepSeek R1/V3, Qwen 2.5 72B, Mistral 7B — Cosmos blockchain decentralized GPU marketplace. Llama 3.1 8B $0.04/1M — ~98% cheaper than GPT-4o. Marketplace dynamics drive prices down: no single company owns the infrastructure.',
    keyPrefix: '',
    keyPlaceholder: 'your-akash-api-key',
    helpUrl: 'https://chatapi.akash.network',
    color: '#FF414D',
  },
  arcee: {
    type: 'arcee',
    name: 'Arcee AI',
    description: 'Arcee Maestro, Nova, Agent, Lite, Blitz, Scribe, Spark, CLI — model merging pioneer. SuperMerging™ combines the best of multiple fine-tuned models. Arcee models outperform models 10x their size. arcee-spark $0.09/1M symmetric — 96% cheaper than GPT-4o.',
    keyPrefix: '',
    keyPlaceholder: 'your-arcee-api-key',
    helpUrl: 'https://docs.arcee.ai',
    color: '#6B46C1',
  },
  centml: {
    type: 'centml',
    name: 'CentML',
    description: 'Llama 3.3 70B, Llama 3.1 8B/70B/405B, DeepSeek R1/V3, Mistral 7B, Qwen 2.5 72B — Canadian GPU efficiency pioneer. Proprietary kernel optimization delivers 2-4x cost efficiency vs standard NVIDIA cloud. Mistral 7B $0.06/1M symmetric — 97% cheaper than GPT-4o.',
    keyPrefix: '',
    keyPlaceholder: 'your-centml-api-key',
    helpUrl: 'https://docs.centml.com',
    color: '#059669',
  },
  venice: {
    type: 'venice',
    name: 'Venice AI',
    description: 'Llama 3.3 70B, Llama 3.1 8B/70B, DeepSeek R1/V3, Qwen 2.5 72B, Mistral 7B — privacy-first inference. No conversation logging, no model training on your data. Founded by Erik Voorhees (ShapeShift). Llama 3.2 3B $0.02/1M — ultra-budget. OpenAI-compatible API.',
    keyPrefix: '',
    keyPlaceholder: 'your-venice-ai-api-key',
    helpUrl: 'https://venice.ai/settings/api',
    color: '#8B5CF6',
  },
  inferless: {
    type: 'inferless',
    name: 'Inferless',
    description: 'Llama 3.3 70B, Llama 3.1 8B/70B, DeepSeek R1, Mistral 7B, Qwen 2.5 72B, Phi-3 Medium, Mixtral 8x7B — serverless GPU inference. YC W23-backed platform: deploy any HuggingFace model in under 60 seconds. Mistral 7B $0.10/1M symmetric — 96% cheaper than GPT-4o input. OpenAI-compatible API.',
    keyPrefix: '',
    keyPlaceholder: 'your-inferless-api-key',
    helpUrl: 'https://docs.inferless.com/getting-started/api-key',
    color: '#E91E8C',
  },
  codestral: {
    type: 'codestral',
    name: 'Mistral AI Codestral',
    description: 'Devstral Small (agentic coding agent), Codestral 22B (256K context, 80+ languages), Codestral Mamba 7B ($0.25/1M symmetric — 90% cheaper than GitHub Copilot API) — Mistral AI\'s dedicated code generation endpoint. Fill-in-the-Middle (FIM) for IDE plugins. Track code AI spend separately from chat AI spend.',
    keyPrefix: '',
    keyPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    helpUrl: 'https://docs.mistral.ai/capabilities/code_generation/',
    color: '#FF7000',
  },
  fluidstack: {
    type: 'fluidstack',
    name: 'Fluidstack',
    description: 'Llama 3.3 70B, Llama 3.1 8B/70B/405B, DeepSeek R1, DeepSeek V3, Mistral 7B, Qwen 2.5 72B — GPU aggregation cloud (H100/H200/A100) that trained Mistral AI, Stability AI, and xAI; now offering serverless LLM inference. Global network from 15+ data centers. OpenAI-compatible API. Mistral 7B $0.09/1M symmetric. fluidstack.io',
    keyPrefix: '',
    keyPlaceholder: 'your-fluidstack-api-key',
    helpUrl: 'https://app.fluidstack.io',
    color: '#6B21A8',
  },
  monsterapi: {
    type: 'monsterapi',
    name: 'Monster API',
    description: 'Llama 3.3 70B, Llama 3.1 8B/70B, DeepSeek R1, Mistral 7B, Gemma 2 9B, Phi-3.5 Mini, Qwen 2.5 72B — Indian GPU marketplace connecting idle GPU capacity worldwide. OpenAI-compatible API. Mistral 7B $0.04/1M symmetric — 98% cheaper than GPT-4o input. 6 of 8 models use symmetric pricing.',
    keyPrefix: '',
    keyPlaceholder: 'your-monsterapi-key',
    helpUrl: 'https://monsterapi.ai/dashboard',
    color: '#F97316',
  },
  coreweave: {
    type: 'coreweave',
    name: 'CoreWeave',
    description: 'Llama 3.3 70B, Llama 3.1 8B/70B/405B, DeepSeek R1, Mistral 7B, Mixtral 8x7B, Qwen 2.5 72B, Llama 3.2 11B Vision — largest NVIDIA GPU cloud, IPO\'d 2025 at $35B+. Enterprise SLAs, H100/A100 clusters. OpenAI-compatible API. Llama 3.3 70B $0.48/1M symmetric. Runs production workloads for OpenAI, Meta, Microsoft.',
    keyPrefix: '',
    keyPlaceholder: 'your-coreweave-api-key',
    helpUrl: 'https://cloud.coreweave.com/api-access',
    color: '#6366F1',
  },
  prem: {
    type: 'prem',
    name: 'Prem AI',
    description: 'Llama 3.3 70B, Llama 3.1 8B/70B/405B, DeepSeek R1, Mistral 7B, Qwen 2.5 72B, Llama 3.2 3B — European privacy-first inference platform (Paris-based, GDPR-native). No data retention, no model training on user data, sovereign AI for enterprises with strict compliance requirements. OpenAI-compatible API. Llama 3.3 70B $0.48/$0.72 per 1M. premai.io',
    keyPrefix: '',
    keyPlaceholder: 'your-prem-api-key',
    helpUrl: 'https://app.premai.io/api_keys',
    color: '#10B981',
  },
  clarifai: {
    type: 'clarifai',
    name: 'Clarifai',
    description: 'Llama 3.3 70B, Llama 3.1 8B/70B/405B, Mistral 7B, DeepSeek R1, DeepSeek V3, Qwen 2.5 72B, Mixtral 8x7B — enterprise AI platform founded by ImageNet 2013 winner Matthew Zeiler. Processes 2.5 billion AI predictions/month for 1,000+ enterprise customers. SOC2, HIPAA, FedRAMP-ready. OpenAI-compatible API. Llama 3.3 70B $0.45/$0.67 per 1M. clarifai.com',
    keyPrefix: '',
    keyPlaceholder: 'your-clarifai-personal-access-token',
    helpUrl: 'https://clarifai.com/settings/security',
    color: '#4F46E5',
  },
  sensenova: {
    type: 'sensenova',
    name: 'SenseTime SenseNova',
    description: "SenseChat-5, SenseChat-5 Turbo, SenseChat-5 Lite, SenseReasoner-Pro, SenseCode-V2, SenseChat-Lite — SenseTime's LLM platform (China's largest AI company at IPO, ImageNet 2015 winner). Serving 100M+ users via OpenAI-compatible API. SenseChat-5 Pro $2.00/$6.00 per 1M; SenseChat-Lite V4 $0.10/$0.30 — 96% cheaper than GPT-4o. platform.sensenova.cn",
    keyPrefix: '',
    keyPlaceholder: 'your-sensenova-api-key',
    helpUrl: 'https://platform.sensenova.cn',
    color: '#E63946',
  },
  ai360: {
    type: 'ai360',
    name: '360 AI',
    description: '360GPT2-Pro, 360GPT-Turbo, 360GPT-Pro, 360GPT-Lite — 360 Security Technology (三六零), China\'s largest cybersecurity company (601360.SZ, 4.5B endpoint clients). OpenAI-compatible API. 360GPT-Lite $0.08/$0.24 per 1M — 97% cheaper than GPT-4o input. ai.360.cn',
    keyPrefix: '',
    keyPlaceholder: 'your-360ai-api-key',
    helpUrl: 'https://ai.360.cn/open',
    color: '#FF4500',
  },
  naver: {
    type: 'naver',
    name: 'NAVER HyperCLOVA X',
    description: 'HCX-003, HCX-DASH-001, HCX-DASH-002, HCX-DASH-003 — NAVER Corporation (KRX: 035420), Korea\'s largest internet company. HyperCLOVA (2021) was the world\'s first non-English large LLM at 82B parameters. HyperCLOVA X is Korea\'s flagship bilingual Korean-English model. Credentials: apiKeyId::serviceKey (both from console.ncloud.com under AI Services > CLOVA Studio > API Keys). HCX-DASH-003 $0.08/$0.24 per 1M — 97% cheaper than GPT-4o input.',
    keyPrefix: '',
    keyPlaceholder: 'your-api-key-id::your-service-key',
    helpUrl: 'https://console.ncloud.com/ai-application-service/clovaStudio',
    color: '#03C75A',
  },
  inflection: {
    type: 'inflection',
    name: 'Inflection AI',
    description: 'Inflection-3 Productivity, Inflection-3 Pi, Inflection-2.5 — co-founded by Mustafa Suleyman (DeepMind co-founder, now Microsoft AI CEO) and Reid Hoffman (LinkedIn co-founder). Raised $1.3B from Microsoft, NVIDIA, Bill Gates. Pivoted from consumer Pi assistant to enterprise model API in 2024. OpenAI-compatible API. Inflection-3 Productivity $1.20/$3.60 per 1M.',
    keyPrefix: '',
    keyPlaceholder: 'your-inflection-api-key',
    helpUrl: 'https://developers.inflection.ai',
    color: '#7C3AED',
  },
  yandex: {
    type: 'yandex',
    name: 'Yandex Cloud',
    description: "YandexGPT 4 Pro, YandexGPT 4 Lite, Llama 3.1 70B — Yandex is Russia's #1 internet company (founded 1997, >60% Russian search market share, $15B+ revenue, 20,000+ employees). YandexGPT is built on 27 years of Cyrillic NLP expertise. Second Russian sovereign AI provider on LLMeter after GigaChat (Sberbank). OpenAI-compatible Foundation Models API. YandexGPT 4 Lite $0.02/$0.06 per 1M — 99% cheaper than GPT-4o. cloud.yandex.com",
    keyPrefix: '',
    keyPlaceholder: 'your-yandex-iam-token',
    helpUrl: 'https://cloud.yandex.com/en/docs/foundation-models',
    color: '#FF0000',
  },
  fal: {
    type: 'fal',
    name: 'fal.ai',
    description: "Meta Llama 3.3 70B, DeepSeek R1, Qwen 2.5 72B, Google Gemma 2, Microsoft Phi-4, and 50+ open-source models — fal.ai is a16z-backed serverless GPU inference platform (raised $54M Series B, founded 2022). Known for ultra-fast image generation (Flux, SDXL) and LLM inference. OpenAI-compatible API at fal.run/v1. 99% cheaper than GPT-4o for open-source inference. fal.ai/dashboard/keys",
    keyPrefix: '',
    keyPlaceholder: 'your-fal-api-key',
    helpUrl: 'https://fal.ai/dashboard/keys',
    color: '#8B5CF6',
  },
  ionos: {
    type: 'ionos',
    name: 'IONOS AI',
    description: "Meta Llama 3.3 70B, Llama 3.1 70B/8B/405B, Mistral 7B, Mixtral 8x7B, DeepSeek R1, Microsoft Phi-4 — IONOS SE is Germany's largest web hosting provider (8.5M+ customers, owned by United Internet AG with €6.4B revenue, founded 1988). IONOS AI Model Hub runs on Frankfurt data centers — GDPR-native EU inference, zero US cloud dependency. 6 of 8 models symmetric pricing. Mistral 7B at $0.04/1M = cheapest EU AI. cloud.ionos.com/ai-model-hub",
    keyPrefix: '',
    keyPlaceholder: 'your-ionos-api-key',
    helpUrl: 'https://cloud.ionos.com/ai-model-hub',
    color: '#003D8F',
  },
  anyscale: {
    type: 'anyscale',
    name: 'Anyscale',
    description: "Meta Llama 3.3 70B, Llama 3.1 8B/70B/405B, Mistral 7B, Mixtral 8x7B, DeepSeek R1, Qwen 2.5 72B — created by the team behind Ray (100M+ downloads), the distributed computing framework powering ML workloads at OpenAI, Uber, Amazon, and Netflix. A16Z-backed ($100M+ raised). OpenAI-compatible inference API. Llama 3.3 70B at $0.35/1M — 86% cheaper than GPT-4o input. app.endpoints.anyscale.com",
    keyPrefix: '',
    keyPlaceholder: 'your-anyscale-api-key',
    helpUrl: 'https://app.endpoints.anyscale.com',
    color: '#0066FF',
  },
  meta: {
    type: 'meta',
    name: 'Meta Llama API',
    description: "Meta's official inference endpoint for Llama 4 Scout/Maverick, Llama 3.3 70B, Llama 3.1 405B/70B/8B, Llama 3.2 vision — the world's most downloaded open-source model family (1B+ downloads). Created by FAIR (founded 2013), Llama 2 opened the open-weights era in 2023; Llama 3.1 405B matched GPT-4 on key benchmarks. OpenAI-compatible inference API at api.llama.com. Llama 3.3 70B at $0.28/1M — 85% cheaper than GPT-4o.",
    keyPrefix: '',
    keyPlaceholder: 'your-meta-llama-api-key',
    helpUrl: 'https://api.llama.com',
    color: '#0082FB',
  },
  nousresearch: {
    type: 'nousresearch',
    name: 'Nous Research',
    description: "Hermes-3 405B/70B/8B, Hermes-2-Theta 70B, Hermes-2-Pro Mistral 7B/Llama-3 8B, Hermes-3 3B, Nous-Hermes-2 Yi-34B — the open-source fine-tuning lab that built the Hermes series (100M+ Hugging Face downloads). Founded by Teknium and team; pioneered function calling alignment and tool-use fine-tuning on Llama, Mistral, and Yi base models. Hermes-3 405B is the open-source standard for instruction following at scale. Mistral-7B Hermes-2-Pro at $0.07/1M — 97% cheaper than GPT-4o. api.nousresearch.com",
    keyPrefix: '',
    keyPlaceholder: 'your-nous-api-key',
    helpUrl: 'https://api.nousresearch.com',
    color: '#7C3AED',
  },
  glhf: {
    type: 'glhf',
    name: 'GLHF Chat',
    description: 'Llama 3.3 70B, DeepSeek R1, Qwen 2.5 72B, Mistral 7B, Gemma 3, and 50+ open-source models — community GPU inference platform. Mistral 7B at $0.04/1M — 99% cheaper than GPT-4o input. OpenAI-compatible API.',
    keyPrefix: 'glhf_',
    keyPlaceholder: 'glhf_...',
    helpUrl: 'https://glhf.chat/users/settings/api',
    color: '#6366F1',
  },
  sakura: {
    type: 'sakura',
    name: 'Sakura Internet',
    description: "Llama 3.3 70B, Llama 3.1 8B, Mistral 7B, Mixtral 8x7B, DeepSeek R1, Qwen 2.5 72B — Japan's largest independent cloud provider (TSE Prime: 3778, founded 1996). H100 GPU AI inference with Japanese data sovereignty. Llama 3.3 70B at $0.45/1M. OpenAI-compatible API at api.sakura.io.",
    keyPrefix: '',
    keyPlaceholder: 'your-sakura-internet-api-key',
    helpUrl: 'https://api.sakura.io',
    color: '#E91E63',
  },
  textsynth: {
    type: 'textsynth',
    name: 'TextSynth',
    description: "Llama 3 70B, Mistral 7B, Mixtral 8x7B, Qwen 2 72B, Code Llama 34B, Gemma 2 9B, DeepSeek R1 — privacy-first LLM inference created by Fabrice Bellard (inventor of FFmpeg, QEMU, TCC, and JSLinux). One-man operation based in France; no training on user data. Mistral 7B at $0.04/1M — 98% cheaper than GPT-4o. OpenAI-compatible API at api.textsynth.com.",
    keyPrefix: '',
    keyPlaceholder: 'your-textsynth-api-key',
    helpUrl: 'https://textsynth.com/settings.html',
    color: '#10B981',
  },
  heurist: {
    type: 'heurist',
    name: 'Heurist AI',
    description: "Llama 3.3 70B, Llama 3.1 70B/8B, Mistral 7B, DeepSeek R1, DeepSeek V3, Qwen 2.5 72B, Phi-3 Mini — decentralized AI inference network on Ethereum ZK (L2). Idle GPU resources rewarded via smart contracts. 4th blockchain network on LLMeter after Corcel (Bittensor), io.net (Solana), and Akash (Cosmos). Mistral 7B at $0.04/1M. OpenAI-compatible API at llm-gateway.heurist.xyz.",
    keyPrefix: 'heurist_',
    keyPlaceholder: 'heurist_...',
    helpUrl: 'https://dev.heurist.ai',
    color: '#6366F1',
  },
  nearai: {
    type: 'nearai',
    name: 'NEAR AI',
    description: "Llama 3.3 70B, Llama 3.1 70B/8B/405B, DeepSeek R1, DeepSeek V3, Mistral 7B, Qwen 2.5 72B — NEAR Protocol's AI inference network. 5th blockchain AI network on LLMeter after Corcel (Bittensor), io.net (Solana), Akash (Cosmos), and Heurist (Ethereum ZK L2). PoS sharding for scalable, low-cost compute. Llama 3.1 8B at $0.04/1M. OpenAI-compatible API at api.near.ai/v1.",
    keyPrefix: '',
    keyPlaceholder: 'your-nearai-api-key',
    helpUrl: 'https://nearai.app',
    color: '#00C08B',
  },
  netmind: {
    type: 'netmind',
    name: 'NetMind AI',
    description: 'Llama 3.3 70B, Llama 3.1 70B/8B/405B, DeepSeek R1, DeepSeek V3, Mistral 7B, Qwen 2.5 72B — community GPU marketplace where contributors share idle capacity and earn NMT token rewards. Founded 2022, based in UK; 250,000+ nodes globally. Community GPU supply drives prices down: Llama 3.1 8B at $0.04/1M, 98% cheaper than GPT-4o. OpenAI-compatible API at api.netmind.ai/inference-api/openai/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-netmind-api-key',
    helpUrl: 'https://netmind.ai',
    color: '#1D4ED8',
  },
  hyperstack: {
    type: 'hyperstack',
    name: 'Hyperstack',
    description: 'Llama 3.3 70B, Llama 3.1 70B/8B/405B, DeepSeek R1, Mistral 7B, Qwen 2.5 72B, Mixtral 8x7B — UK/Netherlands GPU cloud and certified NVIDIA Cloud Partner. H100, H200, and A100 clusters for AI inference and training. Founded 2022, based in London; sustainable data centres powered by Dutch renewable energy. OpenAI-compatible API at infra.hyperstack.cloud/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-hyperstack-api-key',
    helpUrl: 'https://hyperstack.cloud',
    color: '#EA580C',
  },
  gmi: {
    type: 'gmi',
    name: 'GMI Cloud',
    description: 'Llama 3.3 70B, DeepSeek R1, DeepSeek V3, Kimi K2 Agentic, MiniMax M2.1, Qwen3-VL 235B, GLM-4.7, DeepSeek V3.2 — $82M Series A GPU cloud (Oct 2024). Founded 2022 by Alex Yeh in San Jose; pivoted from Bitcoin compute to AI GPU infrastructure. H100/H200 clusters with per-token serverless inference. OpenAI-compatible API at api.gmi-serving.com/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-gmi-cloud-api-key',
    helpUrl: 'https://console.gmicloud.ai',
    color: '#2563EB',
  },
  internlm: {
    type: 'internlm',
    name: 'InternLM',
    description: 'InternLM3 8B/20B, InternLM2.5 7B/20B, InternLM2 Math 20B/34B, InternVL2 8B/26B/76B — top-ranked on C-Eval, CMMLU, and HumanEval benchmarks. Developed by Shanghai AI Laboratory (上海人工智能实验室), a major Chinese research institution founded 2020 and backed by Alibaba, Tencent, ByteDance, and Sequoia China. InternVL2 is among the best open-source vision-language models globally. OpenAI-compatible API at internlm-chat.intern-ai.org.cn/puyu/api/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-internlm-api-key',
    helpUrl: 'https://internlm.intern-ai.org.cn/api/tokens',
    color: '#0EA5E9',
  },
  targon: {
    type: 'targon',
    name: 'Targon',
    description: 'Llama 3.3 70B, Llama 3.1 8B/70B/405B, DeepSeek R1/V3, Mistral 7B, Qwen 2.5 72B — Bittensor subnet 19 decentralized inference network by Nineteen.ai. Community GPU validators earn TAO rewards by serving inference. 6th blockchain AI network on LLMeter. OpenAI-compatible API at api.targon.com/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-targon-api-key',
    helpUrl: 'https://targon.com',
    color: '#6D28D9',
  },
  skywork: {
    type: 'skywork',
    name: 'SkyWork AI',
    description: "Tiangong-2, SkyWork-o1 reasoning, SkyWork MoE 20B, SkyWork 13B/7B Chat — Kunlun Tech's (昆仑万维, SZSE: 300418) AI pivot. China's largest gaming company launched Tiangong (天工) AI in 2023 with OpenAI-compatible API. SkyWork-o1-Preview brings chain-of-thought reasoning. SkyWork-7B-Chat at $0.06/1M — 97% cheaper than GPT-4o input.",
    keyPrefix: '',
    keyPlaceholder: 'your-skywork-api-key',
    helpUrl: 'https://platform.tiangong.cn',
    color: '#FF6B35',
  },
  infermatic: {
    type: 'infermatic',
    name: 'Infermatic',
    description: 'Midnight Rose 103B, WizardLM 2 70B, Llama 3 70B, MythoMax L2 13B, OpenHermes 2.5, Mistral 7B — privacy-first uncensored open-source model hosting. No request logging, no training on user data. Hosts creative and standard open-weights models. All pricing symmetric (input = output). Mistral 7B at $0.07/1M — 97% cheaper than GPT-4o. OpenAI-compatible API at api.infermatic.ai/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-infermatic-api-key',
    helpUrl: 'https://infermatic.ai',
    color: '#7C3AED',
  },
  mancer: {
    type: 'mancer',
    name: 'Mancer',
    description: 'WizardLM 2 8x22B MoE, Midnight Rose 103B, WizardLM 2 70B, MythoMax L2 13B, Noromaid 20B, WizardCoder 33B, Llama 3.1 70B, Llama 3 8B — privacy-first uncensored LLM inference hosted in Europe. No conversation logging, no data retention, no content filtering. All pricing symmetric (input = output). Llama 3 8B at $0.08/1M — 95% cheaper than GPT-4o. OpenAI-compatible API at neuro.mancer.tech/oai/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-mancer-api-key',
    helpUrl: 'https://mancer.tech',
    color: '#8B4513',
  },
  rhymes: {
    type: 'rhymes',
    name: 'Rhymes AI',
    description: 'Aria (multimodal flagship MoE 25.3B, 128K context, native video+image understanding), Aria Text (text-only, faster), Aria Mini (compact, budget) — Italian-founded AI startup (2023) by former Meta AI Research team. First native video-understanding LLM provider on LLMeter. Aria Mini at $0.10/1M — 96% cheaper than GPT-4o input. OpenAI-compatible API at api.rhymes.ai/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-rhymes-api-key',
    helpUrl: 'https://rhymes.ai',
    color: '#E84393',
  },
  primeintellect: {
    type: 'primeintellect',
    name: 'Prime Intellect',
    description: 'INTELLECT-1 (10B — trained across 112 GPU contributors in 40+ countries, first fully decentralized model training), Llama 3.3 70B ($0.25/1M), DeepSeek R1 (reasoning), Qwen 2.5 72B — San Francisco AI startup (2023) that pioneered PRIME protocol for distributed model training. $15.5M raised. 7th decentralized AI compute network on LLMeter. Llama 3.1 8B at $0.05/1M — 98% cheaper than GPT-4o input. OpenAI-compatible API at api.primeintellect.ai/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-primeintellect-api-key',
    helpUrl: 'https://primeintellect.ai',
    color: '#6366F1',
  },
  exaone: {
    type: 'exaone',
    name: 'LG AI Research (EXAONE)',
    description: 'EXAONE 3.5 7.8B/2.4B Instruct, EXAONE Deep (reasoning), EXAONE 3.0 — LG Corporation\'s AI research lab. 3rd Korean AI provider on LLMeter. EXAONE 3.5 bilingual Korean-English, #1 on Korean benchmarks, competitive with Llama 3.3 70B at 7.8B params. EXAONE Deep reasoning model competitive with o1-level on MATH-500. Apache 2.0 open source. EXAONE 3.5 2.4B at $0.04/1M — 98% cheaper than GPT-4o input. OpenAI-compatible API at api.exaone.ai/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-exaone-api-key',
    helpUrl: 'https://api.exaone.ai',
    color: '#A50034',
  },
  mimo: {
    type: 'mimo',
    name: 'Xiaomi MiMo',
    description: 'MiMo-V2.5-Pro (1M ctx, deep thinking, tool calling, web search), MiMo-V2.5 (multimodal text+image+video, 1M ctx), MiMo-V2-Flash ($0.01/1M input — 99.6% cheaper than GPT-4o) — Xiaomi (小米科技, HKEX: 1810), world\'s 3rd largest smartphone maker. Founded 2010 by Lei Jun; $46B+ revenue; 600M+ MIUI users. Also makes Smart TVs, IoT devices, and electric vehicles (SU7, 2024). MiMo-V2.5 adds 1M token context window, multimodal reasoning, and agentic tool use. OpenAI-compatible API at api.xiaomimimo.com/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-mimo-api-key',
    helpUrl: 'https://platform.xiaomimimo.com',
    color: '#FF6900',
  },
  lamini: {
    type: 'lamini',
    name: 'Lamini AI',
    description: 'Llama 3.3 70B ($0.30/$0.50), Llama 3.1 8B ($0.08/$0.12 — 97% cheaper than GPT-4o), Mistral 7B ($0.10/$0.10 symmetric), DeepSeek R1 ($0.55/$2.19 — reasoning), Qwen 2.5 72B ($0.35/$0.35 symmetric), Mixtral 8x7B ($0.30/$0.30 symmetric MoE), Llama 3.1 405B ($2.50/$3.00 — enterprise), Phi-3 Medium 128K ($0.25/$0.25 symmetric) — Lamini (lamini.ai), LLM fine-tuning and inference platform. Founded 2022 by Sharon Zhou (Stanford AI PhD, formerly NVIDIA) and Greg Diamos (co-created NVIDIA Volta architecture, formerly Baidu/NVIDIA/Snowflake). San Francisco. AMD partnership: AMD Instinct MI300X GPUs — the only AMD-powered inference provider on LLMeter. Full fine-tuning → serving loop: train on private data, deploy on the same OpenAI-compatible endpoint. Mistral 7B at $0.10/1M — 96% cheaper than GPT-4o input. OpenAI-compatible API at api.lamini.ai/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-lamini-api-key',
    helpUrl: 'https://docs.lamini.ai',
    color: '#7C3AED',
  },
  intel: {
    type: 'intel',
    name: 'Intel Developer Cloud',
    description: 'Llama 3.3 70B ($0.35/$0.40), Llama 3.1 8B ($0.07/$0.07 symmetric — 98% cheaper than GPT-4o), Mistral 7B ($0.05/$0.05 symmetric — 98% cheaper than GPT-4o), Phi-4 ($0.12/$0.12 symmetric Microsoft), DeepSeek R1 ($0.55/$2.19 — reasoning), Qwen 2.5 72B ($0.32/$0.32 symmetric), Llama 3.1 405B ($1.80/$1.80 symmetric — enterprise), Llama 3.1 70B ($0.30/$0.35) — Intel Corporation (NASDAQ: INTC), Santa Clara CA. Gaudi AI accelerators (Gaudi 3 launched April 2024) compete directly with NVIDIA A100/H100 and AMD Instinct MI300X. 113,000 employees, $54B+ revenue. Intel AI PC initiative: 100M+ AI PCs with Neural Processing Units. 3rd of the Big 3 AI chip companies tracked in LLMeter. 5 of 8 models symmetric pricing. Mistral 7B at $0.05/1M — 98% cheaper than GPT-4o input. OpenAI-compatible API at api.us.gaudi.cloud.intel.com/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-intel-api-key',
    helpUrl: 'https://console.cloud.intel.com',
    color: '#0068B5',
  },
  h2o: {
    type: 'h2o',
    name: 'H2O.ai',
    description: 'H2O Danube 3 4B ($0.15/$0.15 symmetric — compact enterprise, 94% cheaper than GPT-4o), H2O Danube 3 1.8B ($0.06/$0.06 symmetric — ultra-budget), Llama 3.3 70B ($0.40/$0.60), Mistral 7B ($0.07/$0.07 symmetric — cheapest), DeepSeek R1 ($0.55/$2.19 — reasoning), Mixtral 8x7B ($0.30/$0.30 symmetric MoE), Llama 3.1 70B ($0.35/$0.55), Llama 3.1 8B ($0.08/$0.08 symmetric — budget) — H2O.ai, Inc., Mountain View CA. Founded 2012 by Sri Ambati — the ML democratization company that existed before "LLM" was a common phrase. 20,000+ organizations (Goldman Sachs, PayPal, Cigna, Capital One, VISA) run H2O products. $250M+ raised from NVIDIA, IBM, Wells Fargo Strategic Capital, Nexus Venture Partners. Products: H2O-3 (open-source AutoML, 11,000+ GitHub stars), H2OGPT (open-source LLM interface), H2O Wave, H2O AI Cloud (enterprise inference). H2O Danube 3: compact enterprise LLMs (1.8B and 4B) optimized for constrained hardware. 4 of 8 models symmetric pricing. OpenAI-compatible API at api.h2o.ai/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-h2o-api-key',
    helpUrl: 'https://docs.h2o.ai/h2o-ai-cloud',
    color: '#FEC925',
  },
  g42: {
    type: 'g42',
    name: 'G42 Cloud AI',
    description: 'Jais-30B-Chat ($0.30/$0.30 symmetric — Arabic-English flagship, 88% cheaper than GPT-4o), Jais-13B-Chat ($0.15/$0.15 symmetric — mid-range), Jais-6.7B-Chat ($0.08/$0.08 symmetric — budget, 97% cheaper than GPT-4o), Jais-30B ($0.25/$0.25 symmetric — base model), Llama 3.3 70B ($0.40/$0.60 — multilingual), Llama 3.1 70B ($0.35/$0.55), Mistral 7B ($0.07/$0.07 symmetric — cheapest, 97% cheaper than GPT-4o), Qwen 2.5 72B ($0.38/$0.38 symmetric — multilingual) — G42 (Group 42 Holding Ltd), Abu Dhabi, UAE. Founded 2018 by Peng Xiao. Abu Dhabi government-backed AI conglomerate with $50B+ assets under management. Microsoft invested $1.5B in G42 in April 2024 — one of the largest single AI investments ever. JAIS: Arabic-English bilingual LLM series developed jointly with MBZUAI (Mohamed bin Zayed University of AI — world\'s first graduate-level AI university). Jais-30B trained on 72% English + 28% Arabic data; purpose-built for MENA enterprise customers. 2nd UAE sovereign AI provider on LLMeter after AI71 (Falcon by TII). 6 of 8 models symmetric pricing. OpenAI-compatible API at api.g42cloud.com/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-g42-api-key',
    helpUrl: 'https://docs.g42cloud.com/ai',
    color: '#00A86B',
  },
  tensorwave: {
    type: 'tensorwave',
    name: 'TensorWave',
    description: 'Llama 3.3 70B Instruct ($0.35/$0.35 symmetric — flagship, AMD MI300X), Llama 3.1 70B Instruct ($0.30/$0.30 symmetric), Llama 3.1 8B Instruct ($0.08/$0.08 symmetric — budget, 97% cheaper than GPT-4o), Llama 3.1 405B Instruct ($1.60/$1.60 symmetric — enterprise; MI300X 192GB VRAM enables full 405B), DeepSeek R1 ($0.50/$2.00 — reasoning), DeepSeek V3 ($0.20/$0.80), Mistral 7B Instruct ($0.06/$0.06 symmetric — cheapest, 97% cheaper than GPT-4o), Qwen 2.5 72B Instruct ($0.30/$0.30 symmetric — multilingual) — TensorWave, Inc., Phoenix, AZ. Founded 2023. AMD MI300X-based GPU cloud — the first AMD-native cloud built from the ground up with no NVIDIA hardware. AMD MI300X has 192GB HBM3 memory (vs NVIDIA H100\'s 80GB) — 2.4× memory advantage, ideal for large models and MoE architectures. The "AMD moment" in AI: AMD\'s MI300X is the #1 server AI chip revenue driver for AMD in 2024-2025. 2nd AMD-powered inference provider on LLMeter after Lamini AI. 6 of 8 models symmetric pricing. OpenAI-compatible API at api.tensorwave.com/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-tensorwave-api-key',
    helpUrl: 'https://docs.tensorwave.com',
    color: '#ED1C24',
  },
  recursal: {
    type: 'recursal',
    name: 'Recursal AI',
    description: 'RWKV-6 Finch 14B ($0.20/$0.20 symmetric — flagship, 4th non-transformer on LLMeter), RWKV-6 Finch 7B ($0.10/$0.10 symmetric), RWKV-6 Finch 3B ($0.06/$0.06 symmetric — budget), RWKV-5 Eagle 7B ($0.08/$0.08 symmetric), RWKV-6 World 14B ($0.15/$0.15 symmetric — multilingual 100+ languages), RWKV-6 World 7B ($0.08/$0.08 symmetric — multilingual budget), RWKV-4 Raven 14B ($0.12/$0.12 symmetric — instruction-tuned), RWKV-4 World 14B ($0.10/$0.10 symmetric — multilingual legacy) — Recursal AI, San Francisco, CA. Founded 2023 by BlinkDL (Peng Bo). RWKV (Receptance Weighted Key Value) — 100% attention-free architecture: linear time and memory complexity during inference. Fourth non-transformer architecture on LLMeter after Inception AI (Mercury diffusion, Day 80), Liquid AI (LFMs, Day 81), and Zyphra (Zamba Mamba SSM, Day 82). RWKV trains like a Transformer (parallelizable) but infers like an RNN (sequential state) — eliminating the O(n²) attention bottleneck. Eagle (RWKV-5) and Finch (RWKV-6) are the production-grade model families. RWKV World models support 100+ languages trained on multilingual data. All 8 models symmetric pricing (input = output per 1M tokens). OpenAI-compatible API at api.recursal.ai/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-recursal-api-key',
    helpUrl: 'https://docs.recursal.ai',
    color: '#4F46E5',
  },
  voyage: {
    type: 'voyage',
    name: 'Voyage AI',
    description: 'voyage-3 ($0.06/1M — best quality-price balance), voyage-3-lite ($0.02/1M — ultra-budget, 99% cheaper than typical text generation), voyage-code-3 ($0.12/1M — best code embeddings on MTEB, #1 code leaderboard), voyage-3-large ($0.18/1M — highest quality general embeddings), voyage-finance-2 ($0.12/1M — finance domain-specialized), voyage-law-2 ($0.12/1M — legal domain-specialized), voyage-multilingual-2 ($0.12/1M — 30+ language support), voyage-large-2-instruct ($0.12/1M — instruction-following embeddings) — Voyage AI, San Francisco, CA. Founded 2023 by Tengyu Ma (Stanford CS Professor, formerly Meta FAIR) and team. $20M seed from Andreessen Horowitz. First embeddings-focused provider on LLMeter — #1 on MTEB leaderboard for general and code embeddings. Used by Anthropic (official RAG recommendation for Claude), Pinecone, LlamaIndex, LangChain, and Cohere. RAG developers pay for embeddings but most LLM cost monitors only track generation costs. All 8 models: input-only pricing (output_price=0, embeddings produce vectors not tokens). API key starts with pa- prefix. voyageai.com',
    keyPrefix: 'pa-',
    keyPlaceholder: 'pa-...',
    helpUrl: 'https://dash.voyageai.com',
    color: '#6B21A8',
  },
  nomic: {
    type: 'nomic',
    name: 'Nomic AI',
    description: 'nomic-embed-text-v1.5 ($0.10/1M — flagship, only fully open-source Apache 2.0 embedding model competitive on MTEB; 8192 token context; Matryoshka dims for 6× cheaper vector storage), nomic-embed-text-v1.5-long ($0.10/1M — extended context optimized), nomic-embed-text-v1 ($0.10/1M — previous generation, established), nomic-embed-vision-v1.5 ($0.10/1M — multimodal image+text embeddings flagship), nomic-embed-vision-v1 ($0.10/1M — previous generation multimodal), nomic-embed-text-v1-unsupervised ($0.05/1M — 50% cheaper, no contrastive training), nomic-embed-text-v2-moe ($0.15/1M — MoE architecture higher quality), nomic-embed-code ($0.10/1M — code-specialized embeddings) — Nomic AI, New York, NY. Founded 2022 by Brandon Duderstadt (CEO) and Zach Nussbaum (CTO). Second embeddings-focused provider on LLMeter after Voyage AI (Day 128). The only fully open-source (Apache 2.0) embedding model in top MTEB rankings — full training code, dataset, and weights publicly released. Matryoshka representation learning enables truncation to 128 dimensions for 6× cheaper vector storage vs full 768 dims. Customers include enterprise RAG developers needing open-source auditable embeddings with no vendor lock-in. All models: input-only pricing (output_price=0, embeddings produce vectors not tokens). API key starts with nk- prefix. nomic.ai',
    keyPrefix: 'nk-',
    keyPlaceholder: 'nk-...',
    helpUrl: 'https://docs.nomic.ai',
    color: '#10B981',
  },
  jina: {
    type: 'jina',
    name: 'Jina AI',
    description: 'jina-embeddings-v3 ($0.02/1M — flagship, 570M params, MTEB top 10, 89 languages, 8192 ctx, late interaction retrieval), jina-clip-v2 ($0.02/1M — multimodal text+image unified model, 865M params, same model encodes both text and images for true multimodal RAG), jina-clip-v1 ($0.02/1M — previous multimodal, 223M params), jina-embeddings-v2-base-en ($0.01/1M — English-only, Apache 2.0 open-source), jina-embeddings-v2-base-de ($0.01/1M — German-specialized enterprise embeddings), jina-embeddings-v2-base-zh ($0.01/1M — Chinese-English bilingual), jina-embeddings-v2-base-code ($0.01/1M — code-specialized, multi-language programming), jina-colbert-v2 ($0.02/1M — ColBERT late interaction for precise retrieval, 89 languages) — Jina AI GmbH, Berlin, Germany. Founded 2020 by Han Xiao (CEO, ex-Tencent AI Lab) and Michael Berk Yazici. Third embeddings-focused provider on LLMeter after Voyage AI (Day 128) and Nomic AI (Day 129). jina-clip-v2 is a unique multimodal model: the same model encodes both text queries and images, enabling multimodal RAG without separate vision encoders. German and Chinese-specialized models serve non-English enterprise markets. All models: input-only pricing (output_price=0, embeddings produce vectors not tokens). API key starts with jina_ prefix. jina.ai',
    keyPrefix: 'jina_',
    keyPlaceholder: 'jina_...',
    helpUrl: 'https://jina.ai/api-dashboard',
    color: '#F59E0B',
  },
  tenstorrent: {
    type: 'tenstorrent',
    name: 'Tenstorrent',
    description: 'llama-3.3-70b-instruct ($0.35/$0.45 — flagship on Wormhole RISC-V, 91% cheaper than GPT-4o), llama-3.1-70b-instruct ($0.30/$0.40 — previous gen flagship), llama-3.1-8b-instruct ($0.08/$0.08 sym — budget, 97% cheaper than GPT-4o), llama-3.1-405b-instruct ($1.80/$1.80 sym — enterprise, Wormhole 192GB memory fits full 405B), mistral-7b-instruct ($0.05/$0.05 sym — cheapest, 98% cheaper than GPT-4o), deepseek-r1 ($0.55/$2.19 — reasoning flagship), qwen-2.5-72b-instruct ($0.30/$0.30 sym — multilingual), phi-4 ($0.12/$0.12 sym — Microsoft flagship) — Tenstorrent Inc., Santa Clara, CA + Toronto, ON. Founded 2016. CEO: Jim Keller (legendary CPU architect — AMD K7/K8/Zen, Apple A4/A5, Intel, Tesla FSD chip). First RISC-V AI accelerator on LLMeter. Wormhole RISC-V Tensix cores eliminate proprietary ISA lock-in. $693M Series D (2024) — Hyundai, Samsung, BHP, Bezos Expeditions. Closes the Big 5 AI chip story: NVIDIA (Day 1) + AMD/Lamini (Day 122) + Intel Gaudi (Day 123) + Groq LPU + Cerebras WSE + Tenstorrent RISC-V (Day 131). OpenAI-compatible API at api.tenstorrent.ai/v1. tenstorrent.com',
    keyPrefix: '',
    keyPlaceholder: 'tt_...',
    helpUrl: 'https://cloud.tenstorrent.com',
    color: '#7C3AED',
  },
  mixedbread: {
    type: 'mixedbread',
    name: 'MixedBread AI',
    description: 'mxbai-embed-large-v1 ($0.02/1M — MTEB #1 at launch, 335M params, beats OpenAI ada-002 on retrieval benchmarks), mxbai-embed-2d-large-v1 ($0.02/1M — Matryoshka 2D, flexible dims 64→1024, 16× cheaper storage at 64-dim), mxbai-colbert-large-v1 ($0.04/1M — ColBERT late interaction, token-level precision), mxbai-rerank-large-v1 ($0.20/1M — cross-encoder reranker flagship for two-stage RAG), mxbai-rerank-base-v1 ($0.10/1M — budget reranker), mxbai-embed-large-v1-quantized ($0.01/1M — 99.6% cheaper than GPT-4o input) — MixedBread AI GmbH, Berlin, Germany. Founded 2023 by Dominik Sheridan (CEO) and Jonathan Kocmoud (CTO). Fourth embeddings-focused provider on LLMeter after Voyage AI (Day 128), Nomic AI (Day 129), and Jina AI (Day 130). Focused exclusively on high-quality embeddings and reranking — mxbai-embed-large-v1 debuted at #1 on MTEB leaderboard at launch, beating OpenAI text-embedding-ada-002 without frontier compute. mxbai-embed-2d-large-v1: Matryoshka 2D representation enables same model at flexible dimensions — 16× cheaper vector storage at 64-dim vs full 1024-dim. mxbai-colbert-large-v1: ColBERT late interaction for higher-precision retrieval vs single-vector cosine similarity. Cross-encoder rerankers for two-stage RAG pipelines. All models: input-only pricing (output_price=0, embeddings produce vectors not tokens). api.mixedbread.ai',
    keyPrefix: '',
    keyPlaceholder: 'your-mixedbread-api-key',
    helpUrl: 'https://www.mixedbread.ai',
    color: '#F97316',
  },
  stability: {
    type: 'stability',
    name: 'Stability AI',
    description: 'stablelm-2-12b-chat ($0.15/$0.15 sym — flagship, Apache 2.0, 12B params, competitive MMLU/HellaSwag/ARC-Challenge), stablelm-2-12b ($0.12/$0.12 sym — base model), stablelm-zephyr-3b ($0.06/$0.06 sym — instruction-tuned 3B), stablelm-3b-4e1t ($0.05/$0.05 sym — base 3B), stablelm-2-zephyr-1_6b ($0.04/$0.04 sym — instruction-tuned 1.6B), stablelm-2-1_6b-chat ($0.04/$0.04 sym — ultra-compact, 98% cheaper than GPT-4o), stablecode-3b ($0.06/$0.06 sym — code), stablecode-instruct-alpha-3b ($0.07/$0.07 sym — code instruction-tuned) — Stability AI, London, UK. Founded 2020 by Emad Mostaque. Creator of Stable Diffusion — the open-source image generation model that launched the AI art revolution (10M+ downloads, $101M raised at $1B+ valuation from Coatue Management, Lightspeed, O\'Shaughnessy Ventures). First UK-headquartered AI foundation model lab on LLMeter. StableLM 2: Apache 2.0 open-source language models — deploy commercially without usage restrictions. After CEO transition (Emad Mostaque resigned March 2024), Prem Akkaraju became CEO, company refocused on enterprise API services. All 8 models fully symmetric pricing (input = output per 1M tokens). API key starts with sk- prefix. api.stability.ai',
    keyPrefix: 'sk-',
    keyPlaceholder: 'sk-...',
    helpUrl: 'https://platform.stability.ai/docs',
    color: '#3B82F6',
  },
  octoai: {
    type: 'octoai',
    name: 'OctoAI',
    description: 'meta-llama-3.3-70b-instruct ($0.28/$0.45 — flagship, TVM-compiled, 89% cheaper than GPT-4o), meta-llama-3.1-70b-instruct ($0.25/$0.40 — standard flagship), meta-llama-3.1-8b-instruct ($0.05/$0.05 sym — budget, 98% cheaper than GPT-4o), meta-llama-3.1-405b-instruct ($2.00/$2.50 — enterprise), deepseek-r1 ($0.55/$2.19 — reasoning), mistral-7b-instruct-v0.3 ($0.06/$0.06 sym — cheapest on platform), mixtral-8x7b-instruct-v0.1 ($0.20/$0.20 sym — MoE), qwen-2.5-72b-instruct ($0.32/$0.32 sym — multilingual) — OctoAI, San Francisco, CA. Founded 2018 as OctoML by Luis Ceze (University of Washington CSE), Thierry Moreau (UW CSE), and Tianqi Chen (creator of Apache TVM neural network compiler and XGBoost). Rebranded OctoAI in 2022. $132M raised (a16z, Amplify Partners, Madrona). Apache TVM: the most widely deployed neural network compiler — used by Google, Amazon, Microsoft, ARM, Qualcomm. TVM Auto-Scheduling automatically generates hardware-optimized CUDA/OpenCL/ARM kernels without manual tuning. Tianqi Chen: also created XGBoost (100M+ downloads, the dominant gradient boosting library before neural networks). 4 of 8 models symmetric pricing. OpenAI-compatible API at text.octoai.run/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-octoai-api-key',
    helpUrl: 'https://octoai.cloud/docs',
    color: '#0EA5E9',
  },
  ai2: {
    type: 'ai2',
    name: 'Allen Institute for AI (AI2)',
    description: 'olmo-2-13b-instruct ($0.12/$0.12 sym — flagship, Paul Allen legacy open research), olmo-2-7b-instruct ($0.06/$0.06 sym — budget, 98% cheaper than GPT-4o), tulu-3-70b ($0.18/$0.20 — instruction-tuned RLVR flagship), tulu-3-8b ($0.08/$0.08 sym — instruction-tuned budget), molmo-72b ($0.40/$0.40 sym — multimodal flagship, 84% cheaper than GPT-4o), molmo-7b-d ($0.08/$0.08 sym — multimodal budget), olmo-2-1b ($0.03/$0.03 sym — ultra-compact), olmo-1-7b ($0.05/$0.05 sym — prev gen) — Allen Institute for AI, Seattle WA. Founded 2014 by Paul G. Allen (Microsoft co-founder, 1953–2018). The ONLY AI research nonprofit on LLMeter. OLMo 2: the most truly open LLM — weights + ALL training data (Dolma 3T+ tokens) + training code + eval code. Full scientific reproducibility unlike Llama/Mistral (weights-only). Molmo: open multimodal competitive with GPT-4V, 84% cheaper. Tulu 3: RLVR post-training without human preference labels. OpenAI-compatible API at api.allenai.org/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-ai2-api-key',
    helpUrl: 'https://allenai.org/ai2-api',
    color: '#1E6FAD',
  },
  lighton: {
    type: 'lighton',
    name: 'LightOn AI',
    description: 'alfred-40b-1123 ($0.25/$0.75 — flagship, 40B params, French-English bilingual, 90% cheaper than GPT-4o), alfred-40b-0923 ($0.22/$0.66 — stable release), alfred-40b-1023 ($0.22/$0.66 — Oct stable), alfred-17b-0824 ($0.10/$0.30 — midrange), alfred-7b-0824 ($0.05/$0.15 — compact), meta-llama/llama-3.3-70b-instruct ($0.38/$0.60 — hosted Llama 70B flagship), meta-llama/llama-3.1-8b-instruct ($0.08/$0.08 sym — hosted Llama budget), mistralai/mistral-7b-instruct-v0.3 ($0.06/$0.06 sym — cheapest) — LightOn, Paris, France. Founded 2016 by Laurent Daudet (Professor of Physics, Sorbonne University) and Sylvain Gigan (Professor of Physics, ENS Paris). Origin: LightOn built physical Optical Processing Units (OPUs) — hardware using laser diffraction through random optical media to perform ML matrix multiplications at the speed of light, deployed at French research labs. Pivoted from photonic hardware to GPU-based LLM inference in 2022. Second French AI foundation model lab on LLMeter (after Mistral AI). Alfred-40b-1123 at $0.25/1M input — 90% cheaper than GPT-4o. OpenAI-compatible API at api.lighton.ai/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-lighton-api-key',
    helpUrl: 'https://docs.lighton.ai',
    color: '#7C3AED',
  },
  modular: {
    type: 'modular',
    name: 'Modular AI',
    description: 'meta-llama/llama-3.1-70b-instruct ($0.30/$0.40 — flagship, 88% cheaper than GPT-4o), meta-llama/llama-3.1-8b-instruct ($0.06/$0.06 sym — budget, 98% cheaper), meta-llama/llama-3.3-70b-instruct ($0.33/$0.45), meta-llama/llama-3.1-405b-instruct ($1.60/$1.60 sym — enterprise), mistralai/mistral-7b-instruct ($0.05/$0.05 sym — cheapest, 98% cheaper GPT-4o), mistralai/mistral-nemo-12b-instruct ($0.10/$0.10 sym), mistralai/mixtral-8x7b-instruct ($0.28/$0.28 sym — MoE), qwen/qwen2.5-72b-instruct ($0.28/$0.28 sym — multilingual) — Modular Inc., San José, CA. Founded 2022 by Chris Lattner (creator of LLVM, Clang, Swift, MLIR — 4 iconic compiler tools that power modern computing at Apple, Google, Meta, Microsoft), Tim Davis, and Guido van Rossum (Python creator, advisor/investor). MAX inference engine uses MLIR graph-level compilation to generate hardware-specific kernels at deploy time — 2–3x faster throughput than vLLM on identical hardware. Mojo programming language: Python superset, 68,000x faster than pure Python for custom kernels. First custom-MLIR-compiler AI inference cloud on LLMeter. $130M Series B — SV Angel, GV (Google Ventures). api.modular.com/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-modular-api-key',
    helpUrl: 'https://docs.modular.com/max/api/',
    color: '#F97316',
  },
  infercom: {
    type: 'infercom',
    name: 'Infercom',
    description: 'gpt-oss-120b ($0.24/$0.65 — EU sovereign flagship, SambaNova RDU 713 tok/s fastest in Europe), minimax-m2.7-ultraspeed ($0.66/$2.64 — EU sovereign 192K ctx), minimax-m2.5 ($0.33/$1.32 — EU sovereign 160K ctx), gemma-3-12b-it ($0.22/$0.39 — EU sovereign vision, 91% cheaper than GPT-4o for GDPR workloads), Llama-3.3-70B-Instruct ($0.66/$1.32 — global JP catalog), Meta-Llama-3.1-8B-Instruct ($0.17/$0.28 — global JP catalog budget), DeepSeek-V3.2 ($3.30/$4.95 — global JP catalog), DeepSeek-V3.1 ($3.30/$4.95 — global JP catalog) — Infercom SCS, Luxembourg HQ + Munich Germany (Equinix MU1). Founders: Cem Tufekci (Chairman), Serik Kaldykulov (Co-Founder), Altuğ Eker (Managing Director). Europe\'s First Sovereign AI Inference Provider on SambaNova SN40 RDU chips — not NVIDIA GPUs. SambaNova Reconfigurable Dataflow Units: up to 10x faster than GPU inference, 5x more energy efficient, ~10 kW avg system power vs thousands of kW for GPU clusters. gpt-oss-120b at 713 tok/s — fastest 120B inference in Europe. Data never leaves EU jurisdiction. No US CLOUD Act or PATRIOT Act exposure. ISO 27001:2022 certified. GDPR + EU AI Act compliant. Free tier: €5 credit, no credit card. Priced in EUR (a first on LLMeter). api.infercom.ai/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-infercom-api-key',
    helpUrl: 'https://docs.infercom.ai',
    color: '#1D4ED8',
  },
  vast: {
    type: 'vast',
    name: 'Vast.ai',
    description: 'Llama 3.3 70B ($0.16/$0.16 sym — marketplace flagship, 94% cheaper than GPT-4o), Llama 3.1 8B ($0.03/$0.03 sym — budget, 99% cheaper than GPT-4o), Mistral 7B ($0.04/$0.04 sym — cheapest, 98% cheaper), DeepSeek R1 ($0.45/$1.80 — reasoning), Llama 3.1 405B ($1.40/$1.40 sym — enterprise), Qwen 2.5 72B ($0.18/$0.18 sym — multilingual), DeepSeek V3 ($0.16/$0.64) — Vast.ai, San Francisco 2017, the original peer-to-peer GPU marketplace (before io.net, Akash, Corcel). 30,000+ GPUs from individual owners worldwide. Marketplace competition drives LLM inference 20-40% below centralized cloud pricing. Instant Inference: serverless OpenAI-compatible endpoints. 6 of 8 models symmetric pricing. Llama 3.1 8B at $0.03/1M — 99% cheaper than GPT-4o. api.vast.ai/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-vast-api-key',
    helpUrl: 'https://docs.vast.ai/serverless/inference',
    color: '#FF6B35',
  },
  siloai: {
    type: 'siloai',
    name: 'Silo AI',
    description: 'viking-33b-v0.1 ($0.28/$0.28 sym — flagship, Nordic-language 33B, 89% cheaper than GPT-4o), viking-7b-v0.1 ($0.07/$0.07 sym — budget, 97% cheaper), viking-70b-v0.1 ($0.55/$0.55 sym — enterprise), eurollm-9b-instruct ($0.10/$0.10 sym — EU 24-language model), eurollm-1.7b-instruct ($0.04/$0.04 sym — ultra-budget EU multilingual), viking-33b-instruct ($0.32/$0.32 sym — instruction-tuned), llama-3.1-70b-instruct ($0.45/$0.55 — hosted Llama flagship), llama-3.1-8b-instruct ($0.08/$0.08 sym — hosted Llama budget) — Silo AI, Helsinki, Finland 2017. Founded by Peter Sarlin (CEO, former Bank of Finland researcher). AMD acquired Silo AI for $665M in July 2024 — AMD\'s largest AI software acquisition ever. Viking LLM series: the only Scandinavian-language foundation models on LLMeter — trained natively on Finnish, Swedish, Norwegian, Danish, Icelandic data. Apache 2.0 licensed. EuroLLM co-lead (EU-funded €10M, 24 EU official languages). viking-33b-v0.1 at $0.28/1M — 89% cheaper than GPT-4o for Nordic-language tasks. api.silo.ai/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-siloai-api-key',
    helpUrl: 'https://docs.silo.ai',
    color: '#003580',
  },
  phind: {
    type: 'phind',
    name: 'Phind',
    description: 'Developer AI search + code generation — Phind-70B beats GPT-4 Turbo on HumanEval',
    keyPrefix: '',
    keyPlaceholder: 'pf-...',
    helpUrl: 'https://platform.phind.com',
    color: '#7B61FF',
  },
  bentocloud: {
    type: 'bentocloud',
    name: 'BentoCloud',
    description: 'Managed ML model serving — BentoML open-source framework → cloud platform, 200+ models, OpenAI-compatible API',
    keyPrefix: '',
    keyPlaceholder: 'your-bentocloud-api-key',
    helpUrl: 'https://cloud.bentoml.com',
    color: '#FF6B35',
  },
  kakao: {
    type: 'kakao',
    name: 'Kakao AI',
    description: 'KoGPT Korean language models — KakaoTalk (96% of South Korea, 53M MAU), first open-source Korean GPT-3 scale model, 4th Korean AI provider on LLMeter',
    keyPrefix: '',
    keyPlaceholder: 'your-kakao-rest-api-key',
    helpUrl: 'https://developers.kakao.com',
    color: '#FEE500',
  },
  nlpcloud: {
    type: 'nlpcloud',
    name: 'NLP Cloud',
    description: 'Privacy-first open-source LLM inference — Llama 3.3 70B ($0.35/$0.70), Mixtral 8x7B ($0.25 sym), Mistral 7B ($0.07 sym — cheapest EU inference) — 4th French AI provider on LLMeter, founded 2021 by Julien Salinas (solo developer), no prompt logging, no training on user data, EU servers (France + Ireland), GDPR-compliant',
    keyPrefix: '',
    keyPlaceholder: 'your-nlpcloud-api-key',
    helpUrl: 'https://nlpcloud.io/home/token',
    color: '#4F46E5',
  },
  cerebrium: {
    type: 'cerebrium',
    name: 'Cerebrium',
    description: 'Llama 3.3 70B, Llama 3.1 8B, Mistral 7B, DeepSeek R1, Qwen 2.5 72B — Cape Town South Africa serverless ML inference, YC S22, cold start <250ms, pay-per-millisecond billing. First South African AI inference provider on LLMeter.',
    keyPrefix: '',
    keyPlaceholder: 'your-cerebrium-api-key',
    helpUrl: 'https://dashboard.cerebrium.ai',
    color: '#6C47FF',
  },
  tensoropera: {
    type: 'tensoropera',
    name: 'TensorOpera',
    description: 'Llama 3.3 70B ($0.35/$0.55 — flagship, 87% cheaper than GPT-4o), Llama 3.1 8B ($0.07/$0.07 sym — budget, 97% cheaper), Mistral 7B ($0.07/$0.07 sym — cheapest), DeepSeek R1 ($0.55/$2.19 — reasoning), Qwen 2.5 72B ($0.35/$0.35 sym — multilingual), Mixtral 8x7B ($0.28/$0.28 sym — MoE) — TensorOpera (formerly FedML), San Mateo CA 2020. Founded by Salman Avestimehr (USC Professor, IEEE Fellow) + Chaoyang He (USC PhD). $14M from Samsung NEXT, NVIDIA, Intel Capital. First federated ML research framework to become a commercial LLM inference cloud.',
    keyPrefix: '',
    keyPlaceholder: 'your-tensoropera-api-key',
    helpUrl: 'https://docs.tensoropera.ai',
    color: '#8B5CF6',
  },
  infomaniak: {
    type: 'infomaniak',
    name: 'Infomaniak',
    description: 'Llama 3.3 70B ($0.40/$0.60 — flagship, 84% cheaper than GPT-4o), Llama 3.1 8B ($0.10/$0.10 sym — budget, 96% cheaper), Mistral 7B ($0.08/$0.08 sym — cheapest), DeepSeek R1 ($0.55/$2.19 — reasoning), Qwen 2.5 72B ($0.40/$0.40 sym — multilingual), Mixtral 8x7B ($0.28/$0.28 sym — MoE) — Infomaniak Network AG, Geneva Switzerland 1994. Founded by Serge Frech. Family-owned, 100% renewable energy. First Swiss AI inference provider on LLMeter. Swiss nFADP data sovereignty law (stricter than GDPR). Data never leaves Switzerland.',
    keyPrefix: '',
    keyPlaceholder: 'your-infomaniak-api-key',
    helpUrl: 'https://developer.infomaniak.com',
    color: '#E63A28',
  },
  stackit: {
    type: 'stackit',
    name: 'STACKIT',
    description: 'Llama 3.3 70B ($0.45/$0.65 — flagship, 83% cheaper than GPT-4o), Llama 3.1 8B ($0.12/$0.12 sym — budget, 95% cheaper), Mistral 7B ($0.10/$0.10 sym — cheapest), DeepSeek R1 ($0.60/$2.20 — reasoning), Qwen 2.5 72B ($0.45/$0.45 sym — multilingual), Mixtral 8x7B ($0.32/$0.32 sym — MoE) — Schwarz IT GmbH, Heilbronn Germany 2021. Cloud platform of Schwarz Group (Lidl + Kaufland, €113B revenue). First retail conglomerate\'s sovereign AI cloud on LLMeter. 100% German infrastructure, GDPR by design, no US CLOUD Act exposure.',
    keyPrefix: '',
    keyPlaceholder: 'your-stackit-api-key',
    helpUrl: 'https://docs.stackit.cloud/stackit/en/generative-ai-166674180.html',
    color: '#1A56DB',
  },
  abacusai: {
    type: 'abacusai',
    name: 'Abacus.AI',
    description: 'Llama 3.3 70B ($0.55/$0.75 — flagship, 82% cheaper than GPT-4o), Llama 3.1 8B ($0.15/$0.15 sym — budget, 94% cheaper), Mistral 7B ($0.12/$0.12 sym — cheapest), DeepSeek R1 ($0.75/$2.25 — reasoning), Qwen 2.5 72B ($0.50/$0.50 sym — multilingual), Mixtral 8x7B ($0.45/$0.45 sym — MoE) — San Francisco CA 2019. Founded by Bindu Reddy (ex-Google YouTube Recommendations PM) + Arvind Govindarajan (ex-Uber). $405M raised. First pre-LLM enterprise AutoML company to become an LLM inference provider. ChatLLM Teams serves Fortune 500 (Levi\'s, Gap, DoorDash, Verizon, Cisco).',
    keyPrefix: '',
    keyPlaceholder: 'your-abacusai-api-key',
    helpUrl: 'https://docs.abacus.ai/reference',
    color: '#7C3AED',
  },
  pinecone: {
    type: 'pinecone',
    name: 'Pinecone',
    description: 'llama-text-embed-v2 ($0.02/$0.00 — LLAMA-based dense embeddings flagship), multilingual-e5-large ($0.05/$0.00 — 100+ languages), pinecone-sparse-english-v0 ($0.02/$0.00 — hybrid search), pinecone-rerank-v0 ($0.05/$0.00 — cross-encoder reranker) — San Francisco CA 2019. Founded by Edo Liberty (ex-Head of Amazon AI). $138M raised from a16z. Pioneered the managed vector database category. Pinecone Inference (2024): the only vector database company to offer standalone model inference on LLMeter. 5th embeddings provider.',
    keyPrefix: '',
    keyPlaceholder: 'your-pinecone-api-key',
    helpUrl: 'https://docs.pinecone.io/reference',
    color: '#10B981',
  },
  nexusflow: {
    type: 'nexusflow',
    name: 'NexusFlow',
    description: 'gorilla-openfunctions-v2 ($0.10/$0.10 sym — 7B Apache 2.0 first open-source model to outperform GPT-4 on function calling, 96% cheaper), nexus-raven-v2-13b ($0.18/$0.18 sym — 13B human-level tool calling), Llama 3.3 70B ($0.35/$0.55 — general flagship), DeepSeek R1 ($0.55/$2.19 — reasoning) — Berkeley CA 2023. Founded by Shishir Patil (Berkeley PhD, lead author Gorilla LLM paper) + Tianjun Zhang + Lianmin Zheng (creator of vLLM). UC Berkeley Sky Computing Lab lineage (Apache Spark, Ray.io, vLLM). Berkeley Function Calling Leaderboard (BFCL) — the definitive tool-use benchmark used by OpenAI, Anthropic, Google — created by NexusFlow. First purpose-built function-calling LLM inference provider on LLMeter.',
    keyPrefix: '',
    keyPlaceholder: 'your-nexusflow-api-key',
    helpUrl: 'https://docs.nexusflow.ai',
    color: '#7C3AED',
  },
  regolo: {
    type: 'regolo',
    name: 'Regolo.ai',
    description: 'llama-3.1-8b-instruct ($0.09/$0.09 sym — ultra-budget 96% cheaper GPT-4o), mistral-7b-instruct ($0.11/$0.11 sym — EU-native standard), llama-3.3-70b-instruct ($0.66/$2.97 — flagship 82% cheaper GPT-4o), deepseek-r1 ($0.55/$2.20 — sovereign reasoning), qwen2.5-72b-instruct ($1.10/$1.10 sym — multilingual), llama-3.1-405b-instruct ($2.20/$6.60 — enterprise) — Italy 2025. Launched March 2025 by Seeweb S.r.l. (Italy\'s first cloud company, founded 1998, DHH Group Euronext Growth Milan). Data centers in Frosinone and Milan — 100% Italian sovereign infrastructure, no US CLOUD Act. FIRST Italian AI inference provider on LLMeter. Second EUR-priced provider on LLMeter. Italy is the 7th European country with sovereign AI inference on LLMeter.',
    keyPrefix: '',
    keyPlaceholder: 'your-regolo-api-key',
    helpUrl: 'https://docs.regolo.ai',
    color: '#009246',
  },
  heroku: {
    type: 'heroku',
    name: 'Heroku Managed Inference',
    description: 'claude-3-5-sonnet-20241022 ($3.00/$15.00 — Anthropic flagship), claude-3-haiku-20240307 ($0.25/$1.25 — budget 90% cheaper GPT-4o), meta-llama/Llama-3.3-70B-Instruct ($0.75/$0.90 — Meta flagship 70% cheaper GPT-4o), meta-llama/Llama-3.1-8B-Instruct ($0.18/$0.18 sym — budget 93% cheaper), cohere/command-r-plus ($3.00/$15.00 — multilingual enterprise), cohere/command-r ($0.50/$1.50 — standard) — San Francisco CA 2007. Founded by Adam Wiggins, James Lindenbaum, Orion Henry. Acquired by Salesforce $212M December 2010. Invented PaaS (Platform as a Service): git push heroku main, Heroku Buildpacks (standard for Dokku/Render/Railway/Fly.io), Heroku Dynos (original serverless compute). 7M+ developers, 600K+ deployed apps. Heroku Managed Inference (2024): OpenAI-compatible at us.inference.heroku.com/v1. FIRST PaaS pioneer to offer native LLM inference on LLMeter.',
    keyPrefix: '',
    keyPlaceholder: 'your-heroku-api-key',
    helpUrl: 'https://devcenter.heroku.com/articles/heroku-inference',
    color: '#430098',
  },
  predictionguard: {
    type: 'predictionguard',
    name: 'Prediction Guard',
    description: 'Hermes-2-Pro-Llama-3-8B ($0.20/$0.20 sym — NousResearch Llama 3 fine-tune, function calling), Hermes-2-Pro-Mistral-7B ($0.14/$0.14 sym — structured output), Neural-Chat-7B ($0.14/$0.14 sym — Intel-optimized), deepseek-coder-6.7b-instruct ($0.14/$0.14 sym — code specialist), llama-3.1-8b-instruct ($0.20/$0.20 sym — Meta Llama 3.1), llama-3.1-70b-instruct ($0.65/$0.80 — flagship enterprise), Llama-3.2-11B-Vision-Instruct ($0.26/$0.26 sym — multimodal), llava-1.5-7b-hf ($0.14/$0.14 sym — vision-language) — Muncie Indiana 2021. FIRST HIPAA-eligible no-logging LLM inference provider on LLMeter. FIRST Midwest-headquartered AI inference provider on LLMeter. Every prompt processed under HIPAA BAA terms — never logged, never used for training. SOC 2 Type II certified. Target: healthcare, legal, financial institutions with regulated data. OpenAI-compatible API at api.predictionguard.com.',
    keyPrefix: '',
    keyPlaceholder: 'your-predictionguard-api-key',
    helpUrl: 'https://docs.predictionguard.com',
    color: '#0ea5e9',
  },
  modal: {
    type: 'modal',
    name: 'Modal Labs',
    description: 'meta-llama/Llama-3.3-70B-Instruct ($0.35/$0.50 — flagship, 86% cheaper GPT-4o), meta-llama/Llama-3.1-8B-Instruct ($0.07/$0.07 sym — budget, 97% cheaper), meta-llama/Llama-3.1-405B-Instruct ($1.80/$1.80 sym — enterprise), mistralai/Mistral-7B-Instruct-v0.3 ($0.06/$0.06 sym — cheapest, 97% cheaper), deepseek-ai/DeepSeek-R1 ($0.55/$2.19 — reasoning), Qwen/Qwen2.5-72B-Instruct ($0.35/$0.35 sym — multilingual), deepseek-ai/DeepSeek-V3 ($0.16/$0.64 — open-source flagship) — New York City / San Francisco 2021. Founded by Erik Bernhardsson (formerly Spotify ML Platform VP — built Discover Weekly backend, created Luigi data pipeline framework). FIRST serverless GPU compute platform to offer OpenAI-compatible LLM inference on LLMeter. Container snapshot technology: cold start <1s. Pay-per-millisecond billing. Python-native infrastructure. $110M raised from a16z, Redpoint Ventures. OpenAI-compatible API at api.modal.run/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-modal-api-token',
    helpUrl: 'https://modal.com/docs/guide/inference',
    color: '#6d28d9',
  },
  hetzner: {
    type: 'hetzner',
    name: 'Hetzner Cloud AI',
    description: 'llama-3.3-70b-instruct ($0.20/$0.30 — flagship, 92% cheaper GPT-4o), llama-3.1-8b-instruct ($0.04/$0.04 sym — budget, 98% cheaper), mistral-7b-instruct ($0.03/$0.03 sym — cheapest 98% cheaper), deepseek-r1 ($0.35/$1.40 — reasoning), qwen2.5-72b-instruct ($0.20/$0.20 sym — multilingual), mixtral-8x7b-instruct ($0.18/$0.18 sym — MoE), phi-4 ($0.08/$0.16 — Microsoft SLM) — Gunzenhausen Bavaria Germany 1997. Founded by Martin Hetzner + Stephan Hetzner (brothers). Bootstrapped, family-owned, no VC. FIRST bootstrapped founder-led German cloud provider on LLMeter. Every other German provider (IONOS/1&1, STACKIT/Schwarz Group) is a corporate subsidiary. Known for pricing 60–70% below AWS/Azure/GCP. 1.5M+ servers deployed. GDPR/German privacy, no US CLOUD Act. OpenAI-compatible API at inference.hetzner.cloud/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-hetzner-api-token',
    helpUrl: 'https://docs.hetzner.cloud/ai-inference',
    color: '#D50C2D',
  },
  gaianet: {
    type: 'gaianet',
    name: 'GaiaNet',
    description: 'llama-3.3-70b-instruct ($0.18/$0.18 sym — flagship, 93% cheaper GPT-4o), llama-3.1-8b-instruct ($0.04/$0.04 sym — budget, 98% cheaper), llama-3.2-3b-instruct ($0.02/$0.02 sym — ultra-compact, 99% cheaper), mistral-7b-instruct ($0.03/$0.03 sym — cheapest), phi-3-mini-4k-instruct ($0.02/$0.02 sym — ultra-budget SLM), qwen2.5-7b-instruct ($0.04/$0.04 sym — multilingual), gemma-2-9b-it ($0.05/$0.05 sym — Google open-source), deepseek-r1 ($0.15/$0.60 — reasoning) — San Francisco / Singapore 2023. Founded by Michael Yuan (co-creator of WasmEdge, the CNCF WebAssembly runtime). FIRST WebAssembly-based decentralized AI inference network on LLMeter. Every other decentralized network (io.net, Akash, Corcel, Heurist, NEAR, Targon, Prime Intellect) uses Docker+CUDA. GaiaNet nodes run models via WasmEdge sandboxing — portable, secure inference on any hardware. 8th decentralized AI compute network on LLMeter. Each node carries custom knowledge (RAG) + persona for specialist AI agents. $10M+ raised from Polychain Capital, IOSG Ventures. OpenAI-compatible API at api.gaianet.ai/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-gaianet-api-key',
    helpUrl: 'https://docs.gaianet.ai',
    color: '#6366F1',
  },
  plamo: {
    type: 'plamo',
    name: 'PLaMo',
    description: 'plamo-100b ($0.60/$1.80 — flagship 100B trilingual Japanese/English/Chinese, 76% cheaper GPT-4o), plamo-1-prime ($0.40/$1.20 — premium), plamo-1-regular ($0.15/$0.45 — standard), plamo-13b ($0.10/$0.30 — enterprise 13B), plamo-1-turbo ($0.08/$0.24 — fast), plamo-1-mini ($0.03/$0.09 — ultra-budget 99% cheaper GPT-4o), llama-3.3-70b-instruct ($0.20/$0.25 — hosted flagship), mistral-7b-instruct ($0.04/$0.04 sym — cheapest 98% cheaper GPT-4o) — Tokyo, Japan. Founded March 2014 by Toru Nishikawa + Ryosuke Okuta. Creators of Chainer (2015) — Japan\'s first define-by-run deep learning framework that influenced PyTorch\'s dynamic graph design. Toyota Motor ¥10.5B investment for autonomous driving AI. FANUC industrial robot AI. First robotics-AI research company to offer LLM inference on LLMeter. PLaMo-100B: 100B parameter trilingual model (Japanese + English + Chinese). Second Japanese AI inference provider on LLMeter (after Sakura Internet). OpenAI-compatible API at api.preferredai.jp/v1.',
    keyPrefix: '',
    keyPlaceholder: 'your-plamo-api-key',
    helpUrl: 'https://docs.preferredai.jp',
    color: '#0EA5E9',
  },
  salad: {
    type: 'salad',
    name: 'SaladCloud',
    description: 'llama-3.3-70b-instruct ($0.15/$0.15 sym — flagship 94% cheaper GPT-4o), llama-3.1-70b-instruct ($0.13/$0.13 sym — standard 95% cheaper), llama-3.1-8b-instruct ($0.03/$0.03 sym — budget 99% cheaper GPT-4o), mistral-7b-instruct ($0.02/$0.02 sym — cheapest 99% cheaper GPT-4o), deepseek-r1 ($0.40/$1.60 — reasoning consumer GPU pricing), qwen2.5-72b-instruct ($0.15/$0.15 sym — multilingual), gemma-2-9b-it ($0.04/$0.04 sym — Google open-source), phi-3.5-mini-instruct ($0.03/$0.03 sym — Microsoft SLM ultra-budget) — Denver, Colorado. Founded 2018 by Josh Ong (CEO) + Brooks Townsend (CTO). FIRST consumer gaming GPU network for AI inference on LLMeter. 1M+ idle gaming PCs (GeForce RTX 3060–4090, Radeon RX) enrolled as distributed compute. Every other decentralized network uses data center or professional hardware — Salad is the only one using consumer gaming GPUs exclusively. 9th decentralized AI compute network on LLMeter. FIRST Denver / Rocky Mountain AI inference provider on LLMeter. 60–80% below cloud GPU pricing due to idle consumer hardware economics. $3.5M seed from Initialized Capital (Garry Tan, now YC president) + Baseline Ventures. OpenAI-compatible API at api.salad.com/api/public/inference/v1. Auth: Salad-Api-Key header.',
    keyPrefix: '',
    keyPlaceholder: 'your-salad-api-key',
    helpUrl: 'https://docs.salad.com',
    color: '#16A34A',
  },
  lightningai: {
    type: 'lightningai',
    name: 'Lightning AI',
    description: "meta-llama/Llama-3.3-70B-Instruct ($0.25/$0.40 — PyTorch-native flagship 90% cheaper GPT-4o), meta-llama/Llama-3.1-70B-Instruct ($0.22/$0.32 — standard 91% cheaper GPT-4o), meta-llama/Llama-3.1-8B-Instruct ($0.05/$0.05 sym — budget 98% cheaper GPT-4o), mistralai/Mistral-7B-Instruct-v0.3 ($0.04/$0.04 sym — cheapest 98% cheaper GPT-4o), deepseek-ai/DeepSeek-R1 ($0.50/$2.00 — reasoning), Qwen/Qwen2.5-72B-Instruct ($0.25/$0.25 sym — multilingual), google/Gemma-2-9B-IT ($0.05/$0.05 sym — Google open-source), microsoft/Phi-4 ($0.10/$0.10 sym — Microsoft SLM) — San Francisco CA + NYC, 2019. Founded by William Falcon (CEO, creator of PyTorch Lightning 27K+ GitHub stars Linux Foundation project, adopted by Apple Meta Google Goldman Sachs NASA) and Luca Antiga (CTO, PyTorch core contributor, co-creator PyTorch DataLoader). $58M from Coatue, Bain Capital, Index Ventures, NVIDIA, First Round Capital. FIRST open-source ML framework creator to offer commercial AI inference on LLMeter. FIRST PyTorch-native inference platform on LLMeter. Lightning AI Studio: cloud GPU IDE + serverless inference on H100 clusters. Lit-LLM + Lit-GPT open-source inference and training stack (Apache 2.0). OpenAI-compatible API at api.lightning.ai/v1. Auth: Bearer token.",
    keyPrefix: '',
    keyPlaceholder: 'your-lightning-ai-api-key',
    helpUrl: 'https://lightning.ai/docs/inference',
    color: '#792EE5',
  },
  eternalai: {
    type: 'eternalai',
    name: 'EternalAI',
    description: "llama-3.3-70b-instruct ($0.20/$0.20 sym — Bitcoin-inscribed flagship 92% cheaper GPT-4o), llama-3.1-70b-instruct ($0.18/$0.18 sym — standard 93% cheaper GPT-4o), llama-3.1-8b-instruct ($0.04/$0.04 sym — budget 98% cheaper GPT-4o), mistral-7b-instruct ($0.02/$0.02 sym — cheapest 99% cheaper GPT-4o), deepseek-r1 ($0.45/$1.80 — reasoning Bitcoin-secured on-chain), qwen2.5-72b-instruct ($0.18/$0.18 sym — multilingual), gemma-2-9b-it ($0.05/$0.05 sym — Google open-source), phi-3.5-mini-instruct ($0.03/$0.03 sym — Microsoft SLM ultra-budget) — San Francisco, CA. Founded 2024. FIRST Bitcoin-native AI inference network on LLMeter. Model weights inscribed permanently onto the Bitcoin blockchain via Ordinals protocol — censorship-resistant, immutable, verifiable. Every other decentralized inference network (Akash/Cosmos, Heurist/ETH, NEAR AI, Corcel/Bittensor, GaiaNet/WebAssembly) uses blockchain only for payments/incentives while storing weights on traditional servers. EternalAI stores model artifacts ON Bitcoin. 10th decentralized AI compute network on LLMeter. OpenAI-compatible API at api.eternalai.org/v1. Auth: Bearer token.",
    keyPrefix: '',
    keyPlaceholder: 'your-eternalai-api-key',
    helpUrl: 'https://docs.eternalai.org',
    color: '#F7931A',
  },
  sakanaai: {
    type: 'sakanaai',
    name: 'Sakana AI',
    description: "EvoLLM-JP-v1-7B ($0.10/$0.10 sym — Japanese evolutionary LLM flagship 96% cheaper GPT-4o), EvoLLM-JP-A-v1-7B ($0.12/$0.12 sym — enhanced Japanese 95% cheaper GPT-4o), EvoVLM-JP-v1-7B ($0.15/$0.15 sym — Japanese vision-language), Llama-3.3-70B-Instruct ($0.25/$0.40 — general flagship 90% cheaper GPT-4o), Llama-3.1-8B-Instruct ($0.05/$0.05 sym — budget 98% cheaper GPT-4o), Mistral-7B-Instruct ($0.04/$0.04 sym — cheapest 98% cheaper GPT-4o), DeepSeek-R1 ($0.50/$2.00 — reasoning), Qwen2.5-72B-Instruct ($0.20/$0.20 sym — multilingual) — Tokyo, Japan. Founded 2023. FIRST evolutionary AI company on LLMeter. Founded by Llion Jones (CTO, co-author of 'Attention Is All You Need' 2017 Transformer paper — 110,000+ citations, underpins every major LLM) and David Ha (CEO, former Head of Google Brain Tokyo, former Research Director at Google DeepMind). EvoLLM-JP: Japanese LLM built via evolutionary model merging — combines Mistral/Llama/ELYZA weights without training from scratch, outperforms conventionally trained same-size models on Japanese benchmarks. THIRD Japanese AI inference provider on LLMeter (after Sakura Internet Day 106, PLaMo Day 158). OpenAI-compatible API at api.sakana.ai/v1. Auth: Bearer token.",
    keyPrefix: '',
    keyPlaceholder: 'your-sakanaai-api-key',
    helpUrl: 'https://api.sakana.ai/docs',
    color: '#0F766E',
  },
};
